import lessonSectionSamplesHindi from './sectionSamplesHindi';
import lessonSectionSamplesTamil from './sectionSamplesTamil';

const lessonSectionSamples = {
  'lesson-greetings': [
    {
      id: 'greet-s1',
      lessonId: 'lesson-greetings',
      title: 'Greeting basics',
      titleI18n: {
        english: 'Greeting basics',
        tamil: 'வாழ்த்தின் அடிப்படை',
        hindi: 'अभिवादन की मूल बातें',
      },
      textContent: 'Hello! This section shows how to greet politely.',
      textContentI18n: {
        english: 'Hello! This section shows how to greet politely.',
        tamil: 'வணக்கம்! இந்த பகுதி மரியாதையுடன் எப்படி வாழ்த்துவது என்பதை காட்டுகிறது.',
        hindi: 'नमस्ते! यह भाग शिष्ट तरीके से अभिवादन करना दिखाता है।',
      },
      audioUrl: '/audio/greet-s1-narration.mp3',
      highlights: [
        { phrase: 'Hello', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'greet', emphasisType: 'underline', color: 'var(--accent-color)' },
        { phrase: 'politely', emphasisType: 'bold' },
      ],
      visuals: [
        { imageUrl: '/visuals/hello.svg', altText: 'Waving hand saying hello', relatedPhrase: 'Hello', placement: 'inline' },
        { imageUrl: '/visuals/how-are-you.svg', altText: 'People greeting each other politely', relatedPhrase: 'greet politely', placement: 'below' },
      ],
      interactions: [
        {
          id: 'greet-1',
          type: 'true_false',
          question: 'Is "Hello" a friendly greeting?',
          questionI18n: {
            english: 'Is "Hello" a friendly greeting?',
            tamil: '"வணக்கம்" என்பது நட்பான வாழ்த்தா?',
            hindi: 'क्या "नमस्ते" एक दोस्ताना अभिवादन है?',
          },
          questionImageUrl: '/images/greeting-hello.svg',
          questionAudioUrl: '/audio/greet-1-question.mp3',
          correctAnswer: 'True',
          hint: 'Think about what you say when meeting someone new.',
          hintI18n: {
            english: 'Think about what you say when meeting someone new.',
            tamil: 'புதிய ஒருவரை சந்திக்கும்போது நீங்கள் என்ன சொல்வீர்கள் என்பதை நினைத்துப் பாருங்கள்.',
            hindi: 'जब आप किसी नए व्यक्ति से मिलते हैं, तब आप क्या कहते हैं, यह सोचें।',
          },
          explanation: '"Hello" is a common, friendly way to greet someone.',
          explanationI18n: {
            english: '"Hello" is a common, friendly way to greet someone.',
            tamil: '"Hello" என்பது ஒருவரை நட்பாக வாழ்த்தப் பயன்படும் பொதுவான சொல்லாகும்.',
            hindi: '"Hello" किसी को दोस्ताना तरीके से अभिवादन करने का एक आम शब्द है।',
          },
          explanationAudioUrl: '/audio/greet-1-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Great job! "Hello" is a friendly greeting.',
            correctAudioUrl: '/audio/greet-1-correct.mp3',
            incorrect: 'Good effort. Let\'s try again.',
            incorrectAudioUrl: '/audio/greet-1-incorrect.mp3',
          },
          position: 0,
        },
        {
          id: 'greet-2',
          type: 'multiple_choice',
          question: 'Choose a friendly greeting.',
          questionI18n: {
            english: 'Choose a friendly greeting.',
            tamil: 'நட்பான வாழ்த்தைத் தேர்ந்தெடுக்கவும்.',
            hindi: 'एक दोस्ताना अभिवादन चुनें।',
          },
          questionImageUrl: '/images/greeting-options.svg',
          questionAudioUrl: '/audio/greet-2-question.mp3',
          options: ['Hello', 'Goodbye', 'Later'],
          optionsI18n: [
            { english: 'Hello', tamil: 'வணக்கம்', hindi: 'नमस्ते' },
            { english: 'Goodbye', tamil: 'பிரியாவிடை', hindi: 'अलविदा' },
            { english: 'Later', tamil: 'பின்னர்', hindi: 'बाद में' },
          ],
          correctAnswer: 0,
          hint: 'It is a word you say at the start of a conversation.',
          hintI18n: {
            english: 'It is a word you say at the start of a conversation.',
            tamil: 'உரையாடலை தொடங்கும்போது நீங்கள் சொல்லும் ஒரு சொல்.',
            hindi: 'यह वह शब्द है जो आप बातचीत की शुरुआत में कहते हैं।',
          },
          explanation: '"Hello" is a friendly greeting.',
          explanationI18n: {
            english: '"Hello" is a friendly greeting.',
            tamil: '"Hello" என்பது நட்பான வாழ்த்து.',
            hindi: '"Hello" एक दोस्ताना अभिवादन है।',
          },
          explanationAudioUrl: '/audio/greet-2-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Yes! "Hello" is a friendly greeting.',
            correctAudioUrl: '/audio/greet-2-correct.mp3',
            incorrect: 'Nice try. Let\'s pick a greeting used at the start.',
            incorrectAudioUrl: '/audio/greet-2-incorrect.mp3',
          },
          position: 1,
        },
        {
          id: 'greet-3',
          type: 'click',
          question: 'Click the phrase you use to ask about someone.',
          questionI18n: {
            english: 'Click the phrase you use to ask about someone.',
            tamil: 'ஒருவரைப் பற்றி கேட்பதற்கு பயன்படுத்தும் வாக்கியத்தை கிளிக் செய்யவும்.',
            hindi: 'किसी के बारे में पूछने के लिए उपयोग होने वाला वाक्य चुनें।',
          },
          questionImageUrl: '/images/asking-question.svg',
          questionAudioUrl: '/audio/greet-3-question.mp3',
          options: ['How are you?', 'Where is it?', 'See you later'],
          optionsI18n: [
            { english: 'How are you?', tamil: 'நீங்கள் எப்படி இருக்கிறீர்கள்?', hindi: 'आप कैसे हैं?' },
            { english: 'Where is it?', tamil: 'அது எங்கே?', hindi: 'यह कहाँ है?' },
            { english: 'See you later', tamil: 'பின்னர் சந்திப்போம்', hindi: 'फिर मिलेंगे' },
          ],
          correctAnswer: 0,
          hint: 'It is a question about feelings.',
          hintI18n: {
            english: 'It is a question about feelings.',
            tamil: 'இது உணர்ச்சிகளைப் பற்றி கேட்கும் கேள்வி.',
            hindi: 'यह भावनाओं के बारे में पूछा जाने वाला प्रश्न है।',
          },
          explanation: '"How are you?" is used to ask about someone.',
          explanationI18n: {
            english: '"How are you?" is used to ask about someone.',
            tamil: '"How are you?" என்பது ஒருவரின் நிலை/நலத்தை கேட்க பயன்படும் வாக்கியம்.',
            hindi: '"How are you?" किसी का हालचाल पूछने के लिए इस्तेमाल होता है।',
          },
          explanationAudioUrl: '/audio/greet-3-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Nice work! That question checks on someone.',
            correctAudioUrl: '/audio/greet-3-correct.mp3',
            incorrect: 'Good effort. Try the question about feelings.',
            incorrectAudioUrl: '/audio/greet-3-incorrect.mp3',
          },
          position: 2,
        },
        {
          id: 'greet-4',
          type: 'short_answer',
          question: 'Say or type a simple greeting.',
          questionI18n: {
            english: 'Say or type a simple greeting.',
            tamil: 'ஒரு எளிய வாழ்த்தை சொல்லவும் அல்லது டைப் செய்யவும்.',
            hindi: 'एक सरल अभिवादन बोलें या टाइप करें।',
          },
          questionImageUrl: '/images/type-greeting.svg',
          questionAudioUrl: '/audio/greet-4-question.mp3',
          correctAnswer: 'Hello',
          correctAnswerI18n: {
            english: 'Hello',
            tamil: 'வணக்கம்',
            hindi: 'नमस्ते',
          },
          hint: 'Try "Hello".',
          explanation: '"Hello" is a simple, friendly greeting.',
          explanationAudioUrl: '/audio/greet-4-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Great greeting!',
            correctAudioUrl: '/audio/greet-4-correct.mp3',
            incorrect: 'Nice try. A simple greeting is "Hello".',
            incorrectAudioUrl: '/audio/greet-4-incorrect.mp3',
          },
          position: 3,
        },
        {
          id: 'greet-5',
          type: 'multiple_choice',
          question: 'Pick the best reply to "How are you?"',
          questionI18n: {
            english: 'Pick the best reply to "How are you?"',
            tamil: '"நீங்கள் எப்படி இருக்கிறீர்கள்?" என்பதற்கு சிறந்த பதிலைத் தேர்ந்தெடுக்கவும்.',
            hindi: '"आप कैसे हैं?" का सबसे अच्छा जवाब चुनें।',
          },
          questionImageUrl: '/images/responding-greeting.svg',
          questionAudioUrl: '/audio/greet-5-question.mp3',
          options: ['I am good, thank you.', 'Blue.', 'At home.'],
          optionsI18n: [
            { english: 'I am good, thank you.', tamil: 'நான் நன்றாக இருக்கிறேன், நன்றி.', hindi: 'मैं ठीक हूँ, धन्यवाद।' },
            { english: 'Blue.', tamil: 'நீலம்.', hindi: 'नीला।' },
            { english: 'At home.', tamil: 'வீட்டில்.', hindi: 'घर पर।' },
          ],
          correctAnswer: 0,
          hint: 'It is a polite, full reply.',
          explanation: '"I am good, thank you." is a polite response.',
          explanationAudioUrl: '/audio/greet-5-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 40,
          feedback: {
            correct: 'Excellent response!',
            correctAudioUrl: '/audio/greet-5-correct.mp3',
            incorrect: 'Good effort. Choose the polite full reply.',
            incorrectAudioUrl: '/audio/greet-5-incorrect.mp3',
          },
          position: 4,
        },
      ],
      order: 0,
    },
    {
      id: 'greet-s2',
      lessonId: 'lesson-greetings',
      title: 'Friendly phrases',
      titleI18n: {
        english: 'Friendly phrases',
        tamil: 'நட்பான சொற்றொடர்கள்',
        hindi: 'दोस्ताना वाक्य',
      },
      textContent: 'Say "Hello" or "Hi" with a smile. Ask "How are you?"',
      textContentI18n: {
        english: 'Say "Hello" or "Hi" with a smile. Ask "How are you?"',
        tamil: 'சிரிப்புடன் "வணக்கம்" அல்லது "ஹாய்" சொல்லுங்கள். "நீங்கள் எப்படி இருக்கிறீர்கள்?" என்று கேளுங்கள்.',
        hindi: 'मुस्कान के साथ "नमस्ते" या "हाय" कहें। "आप कैसे हैं?" पूछें।',
      },
      audioUrl: '/audio/greet-s2-narration.mp3',
      highlights: [
        { phrase: 'Hello', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'Hi', emphasisType: 'background', color: '#90caf9' },
        { phrase: 'smile', emphasisType: 'underline', color: '#f06292' },
        { phrase: 'How are you?', emphasisType: 'background', color: '#a5d6a7' },
      ],
      visuals: [
        { imageUrl: '/visuals/hello.svg', altText: 'Friendly wave', relatedPhrase: 'Hello', placement: 'inline' },
        { imageUrl: '/visuals/how-are-you.svg', altText: 'Friendly question: How are you?', relatedPhrase: 'How are you?', placement: 'below' },
      ],
      interactions: [
        {
          id: 'greet-s2-1',
          type: 'multiple_choice',
          question: 'What is a friendly way to say hello?',
          questionI18n: {
            english: 'What is a friendly way to say hello?',
            tamil: '"வணக்கம்" சொல்லும் நட்பான வழி எது?',
            hindi: 'हैलो कहने का दोस्ताना तरीका कौन सा है?',
          },
          options: ['Hi!', 'Go away!', 'Not now.'],
          optionsI18n: [
            { english: 'Hi!', tamil: 'ஹாய்!', hindi: 'हाय!' },
            { english: 'Go away!', tamil: 'போகுங்கள்!', hindi: 'चले जाओ!' },
            { english: 'Not now.', tamil: 'இப்போது இல்லை.', hindi: 'अभी नहीं।' },
          ],
          correctAnswer: 0,
          hint: 'Choose the warm and welcoming word.',
          explanation: '"Hi!" is a friendly and casual greeting.',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Perfect! "Hi!" is very friendly.',
            incorrect: 'Try again. Pick the warmest greeting.',
          },
          position: 0,
        },
        {
          id: 'greet-s2-2',
          type: 'true_false',
          question: 'Should you smile when greeting someone?',
          questionI18n: {
            english: 'Should you smile when greeting someone?',
            tamil: 'ஒருவரை வாழ்த்தும்போது சிரிக்க வேண்டுமா?',
            hindi: 'क्या किसी का अभिवादन करते समय मुस्कुराना चाहिए?',
          },
          correctAnswer: 'True',
          hint: 'A smile makes people feel welcome.',
          explanation: 'Smiling when greeting makes you appear friendly and approachable.',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Exactly! A smile makes greetings warmer.',
            incorrect: 'Think about what makes people feel welcome.',
          },
          position: 1,
        },
        {
          id: 'greet-s2-3',
          type: 'short_answer',
          question: 'Type a friendly question you can ask someone.',
          questionI18n: {
            english: 'Type a friendly question you can ask someone.',
            tamil: 'ஒருவரிடம் கேட்கக்கூடிய நட்பான கேள்வியை டைப் செய்யவும்.',
            hindi: 'किसी से पूछने के लिए एक दोस्ताना सवाल टाइप करें।',
          },
          correctAnswer: 'How are you',
          correctAnswerI18n: {
            english: 'How are you',
            tamil: 'நீங்கள் எப்படி இருக்கிறீர்கள்',
            hindi: 'आप कैसे हैं',
          },
          hint: 'Ask about their well-being.',
          explanation: '"How are you?" shows you care about the person.',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Great question! That\'s very friendly.',
            incorrect: 'Try asking "How are you?"',
          },
          position: 2,
        },
      ],
      order: 1,
    },
  ],
  'lesson-vocabulary': [
    {
      id: 'vocab-s1',
      lessonId: 'lesson-vocabulary',
      title: 'Everyday objects',
      textContent: 'Let\u2019s learn simple words for everyday items.',
      audioUrl: '/audio/vocab-s1-narration.mp3',
      highlights: [
        { phrase: 'simple words', emphasisType: 'background', color: '#b39ddb' },
        { phrase: 'everyday items', emphasisType: 'underline', color: 'var(--accent-color)' },
      ],
      visuals: [
        { imageUrl: '/visuals/basic-words.svg', altText: 'Everyday objects and words', relatedPhrase: 'everyday items', placement: 'inline' },
      ],
      interactions: [
        {
          id: 'vocab-1',
          type: 'multiple_choice',
          question: 'Which word matches something you can sit on?',
          questionImageUrl: '/images/chair.svg',
          questionAudioUrl: '/audio/vocab-1-question.mp3',
          options: ['Chair', 'Apple', 'Rain'],
          correctAnswer: 'Chair',
          hint: 'Think of furniture you use every day.',
          explanation: 'A chair is furniture you sit on.',
          explanationAudioUrl: '/audio/vocab-1-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Yes! A chair is something you can sit on.',
            correctAudioUrl: '/audio/vocab-1-correct.mp3',
            incorrect: 'Good effort. Try the word for furniture you sit on.',
            incorrectAudioUrl: '/audio/vocab-1-incorrect.mp3',
          },
          position: 0,
        },
        {
          id: 'vocab-2',
          type: 'multiple_choice',
          question: 'Which word matches something you can eat?',
          questionImageUrl: '/images/apple.svg',
          questionAudioUrl: '/audio/vocab-2-question.mp3',
          options: ['Apple', 'Chair', 'Book'],
          correctAnswer: 'Apple',
          hint: 'It is a fruit.',
          explanation: 'An apple is a fruit you can eat.',
          explanationAudioUrl: '/audio/vocab-2-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Nice! An apple is something you can eat.',
            correctAudioUrl: '/audio/vocab-2-correct.mp3',
            incorrect: 'Nice try. Look for the fruit.',
            incorrectAudioUrl: '/audio/vocab-2-incorrect.mp3',
          },
          position: 1,
        },
        {
          id: 'vocab-3',
          type: 'click',
          question: 'Click the word for something you can read.',
          questionImageUrl: '/images/book.svg',
          questionAudioUrl: '/audio/vocab-3-question.mp3',
          options: ['Book', 'Cloud', 'Shoe'],
          correctAnswer: 'Book',
          hint: 'You open it to see words.',
          explanation: 'A book is something you read.',
          explanationAudioUrl: '/audio/vocab-3-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Great choice! A book is for reading.',
            correctAudioUrl: '/audio/vocab-3-correct.mp3',
            incorrect: 'Good effort. Try the item you can read.',
            incorrectAudioUrl: '/audio/vocab-3-incorrect.mp3',
          },
          position: 2,
        },
        {
          id: 'vocab-4',
          type: 'short_answer',
          question: 'Say or type a simple word for a place you live.',
          questionImageUrl: '/images/home.svg',
          questionAudioUrl: '/audio/vocab-4-question.mp3',
          correctAnswer: 'Home',
          hint: 'Think about where you sleep.',
          explanation: 'Home is the place you live.',
          explanationAudioUrl: '/audio/vocab-4-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Great word!',
            correctAudioUrl: '/audio/vocab-4-correct.mp3',
            incorrect: 'Nice try. A simple word is "Home".',
            incorrectAudioUrl: '/audio/vocab-4-incorrect.mp3',
          },
          position: 3,
        },
        {
          id: 'vocab-5',
          type: 'multiple_choice',
          question: 'Pick the word that means something you wear on your feet.',
          questionImageUrl: '/images/shoe.svg',
          questionAudioUrl: '/audio/vocab-5-question.mp3',
          options: ['Shoe', 'Leaf', 'Cloud'],
          correctAnswer: 'Shoe',
          hint: 'You wear it with socks.',
          explanation: 'A shoe is worn on your foot.',
          explanationAudioUrl: '/audio/vocab-5-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 40,
          feedback: {
            correct: 'Excellent! A shoe goes on your foot.',
            correctAudioUrl: '/audio/vocab-5-correct.mp3',
            incorrect: 'Good effort. Choose the thing you wear.',
            incorrectAudioUrl: '/audio/vocab-5-incorrect.mp3',
          },
          position: 4,
        },
      ],
      order: 0,
    },
    {
      id: 'vocab-s2',
      lessonId: 'lesson-vocabulary',
      title: 'People and places',
      textContent: 'Practice words for people and places you see daily.',
      audioUrl: '/audio/vocab-s2-narration.mp3',
      highlights: [
        { phrase: 'people', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'places', emphasisType: 'background', color: '#90caf9' },
        { phrase: 'daily', emphasisType: 'underline', color: '#f06292' },
      ],
      visuals: [
        { imageUrl: '/visuals/sun.svg', altText: 'Sun icon representing daily life', relatedPhrase: 'daily', placement: 'inline' },
      ],
      interactions: [
        {
          id: 'vocab-s2-1',
          type: 'multiple_choice',
          question: 'Where do you go to buy food?',
          options: ['Store', 'Sky', 'Tree'],
          correctAnswer: 'Store',
          hint: 'You go shopping there.',
          explanation: 'A store is a place where you buy things like food.',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Yes! You buy food at a store.',
            incorrect: 'Think about where people shop.',
          },
          position: 0,
        },
        {
          id: 'vocab-s2-2',
          type: 'click',
          question: 'Click the word for a person who teaches.',
          options: ['Teacher', 'Leaf', 'Door'],
          correctAnswer: 'Teacher',
          hint: 'This person helps you learn.',
          explanation: 'A teacher is someone who helps you learn new things.',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Excellent! A teacher helps you learn.',
            incorrect: 'Try the word for someone who teaches.',
          },
          position: 1,
        },
        {
          id: 'vocab-s2-3',
          type: 'short_answer',
          question: 'Type a word for a person in your family.',
          correctAnswer: 'Mother',
          hint: 'Think of mom, dad, or sister.',
          explanation: 'Family members include mother, father, sister, and brother.',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Great! That\'s a family member.',
            incorrect: 'Try words like mother, father, or sister.',
          },
          position: 2,
        },
      ],
      order: 1,
    },
    {
      id: 'vocab-s3',
      lessonId: 'lesson-vocabulary',
      title: 'Action words',
      textContent: 'Say simple action words like "eat", "walk", and "read".',
      audioUrl: '/audio/vocab-s3-narration.mp3',
      highlights: [
        { phrase: 'action words', emphasisType: 'background', color: '#a5d6a7' },
        { phrase: 'eat', emphasisType: 'background', color: '#ffab91' },
        { phrase: 'walk', emphasisType: 'background', color: '#90caf9' },
        { phrase: 'read', emphasisType: 'background', color: '#ce93d8' },
      ],
      visuals: [
        { imageUrl: '/visuals/speech.svg', altText: 'Speech bubble for saying action words', relatedPhrase: 'Say', placement: 'below' },
      ],
      interactions: [
        {
          id: 'vocab-s3-1',
          type: 'multiple_choice',
          question: 'What action do you do with food?',
          options: ['Eat', 'Fly', 'Sleep'],
          correctAnswer: 'Eat',
          hint: 'You do this when you are hungry.',
          explanation: 'Eat is the action of consuming food.',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Perfect! You eat food.',
            incorrect: 'Think about what you do with food.',
          },
          position: 0,
        },
        {
          id: 'vocab-s3-2',
          type: 'click',
          question: 'Click the action you do with your legs.',
          options: ['Walk', 'Think', 'Sing'],
          correctAnswer: 'Walk',
          hint: 'You move from one place to another.',
          explanation: 'Walk means to move by using your legs.',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Yes! You walk with your legs.',
            incorrect: 'Try the action that uses your legs.',
          },
          position: 1,
        },
        {
          id: 'vocab-s3-3',
          type: 'short_answer',
          question: 'Type an action you do with a book.',
          correctAnswer: 'Read',
          hint: 'You look at the words.',
          explanation: 'Read is the action of looking at and understanding written words.',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Great! You read a book.',
            incorrect: 'Try the word "read".',
          },
          position: 2,
        },
      ],
      order: 2,
    },
  ],
  'lesson-numbers': [
    {
      id: 'num-s1',
      lessonId: 'lesson-numbers',
      title: 'Counting up',
      textContent: 'Count from one to five. Name a color for each number.',
      audioUrl: '/audio/num-s1-narration.mp3',
      highlights: [
        { phrase: 'Count', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'one to five', emphasisType: 'underline', color: 'var(--accent-color)' },
        { phrase: 'color', emphasisType: 'bold' },
      ],
      visuals: [
        { imageUrl: '/visuals/numbers.svg', altText: 'Numbers one two three', relatedPhrase: 'Count', placement: 'inline' },
      ],
      interactions: [
        {
          id: 'numbers-1',
          type: 'click',
          question: 'Click the number that comes after 2.',
          questionImageUrl: '/images/number-sequence.svg',
          questionAudioUrl: '/audio/numbers-1-question.mp3',
          options: ['1', '3', '5'],
          correctAnswer: '3',
          hint: 'Count upward: 1, 2, 3.',
          explanation: 'The number after 2 is 3.',
          explanationAudioUrl: '/audio/numbers-1-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Great job! 3 comes after 2.',
            correctAudioUrl: '/audio/numbers-1-correct.mp3',
            incorrect: 'Good effort. Count up: 1, 2, 3.',
            incorrectAudioUrl: '/audio/numbers-1-incorrect.mp3',
          },
          position: 0,
        },
        {
          id: 'numbers-2',
          type: 'multiple_choice',
          question: 'Which number comes after 4?',
          questionImageUrl: '/images/counting-4-5.svg',
          questionAudioUrl: '/audio/numbers-2-question.mp3',
          options: ['3', '5', '6'],
          correctAnswer: '5',
          hint: 'Count forward: 4, 5.',
          explanation: 'The number after 4 is 5.',
          explanationAudioUrl: '/audio/numbers-2-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Nice! 5 comes after 4.',
            correctAudioUrl: '/audio/numbers-2-correct.mp3',
            incorrect: 'Nice try. Count forward to find 5.',
            incorrectAudioUrl: '/audio/numbers-2-incorrect.mp3',
          },
          position: 1,
        },
        {
          id: 'numbers-3',
          type: 'multiple_choice',
          question: 'Which set has three items?',
          questionImageUrl: '/images/counting-stars.svg',
          questionAudioUrl: '/audio/numbers-3-question.mp3',
          options: ['***', '**', '****'],
          correctAnswer: '***',
          hint: 'Count the stars.',
          explanation: 'Three stars means 3 items.',
          explanationAudioUrl: '/audio/numbers-3-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Great counting!',
            correctAudioUrl: '/audio/numbers-3-correct.mp3',
            incorrect: 'Good effort. Count the stars carefully.',
            incorrectAudioUrl: '/audio/numbers-3-incorrect.mp3',
          },
          position: 2,
        },
        {
          id: 'numbers-4',
          type: 'short_answer',
          question: 'Say or type the number after 1.',
          questionImageUrl: '/images/number-1-2.svg',
          questionAudioUrl: '/audio/numbers-4-question.mp3',
          correctAnswer: '2',
          hint: 'Count: 1, 2.',
          explanation: 'The number after 1 is 2.',
          explanationAudioUrl: '/audio/numbers-4-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Yes! The answer is 2.',
            correctAudioUrl: '/audio/numbers-4-correct.mp3',
            incorrect: 'Nice try. The answer is 2.',
            incorrectAudioUrl: '/audio/numbers-4-incorrect.mp3',
          },
          position: 3,
        },
        {
          id: 'numbers-5',
          type: 'multiple_choice',
          question: 'Choose the correct order from 1 to 3.',
          questionImageUrl: '/images/number-order.svg',
          questionAudioUrl: '/audio/numbers-5-question.mp3',
          options: ['1, 2, 3', '1, 3, 2', '2, 1, 3'],
          correctAnswer: '1, 2, 3',
          hint: 'Start at 1 and count up.',
          explanation: 'The correct order is 1, 2, 3.',
          explanationAudioUrl: '/audio/numbers-5-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 40,
          feedback: {
            correct: 'Excellent ordering!',
            correctAudioUrl: '/audio/numbers-5-correct.mp3',
            incorrect: 'Good effort. Start at 1 and count up.',
            incorrectAudioUrl: '/audio/numbers-5-incorrect.mp3',
          },
          position: 4,
        },
      ],
      order: 0,
    },
    {
      id: 'num-s2',
      lessonId: 'lesson-numbers',
      title: 'Number pairs',
      textContent: 'Match numbers with the correct number of objects.',
      audioUrl: '/audio/num-s2-narration.mp3',
      highlights: [
        { phrase: 'Match', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'numbers', emphasisType: 'underline', color: 'var(--accent-color)' },
        { phrase: 'objects', emphasisType: 'bold' },
      ],
      visuals: [
        { imageUrl: '/visuals/numbers.svg', altText: 'Counting objects', relatedPhrase: 'numbers', placement: 'inline' },
      ],
      interactions: [
        {
          id: 'num-s2-1',
          type: 'multiple_choice',
          question: 'How many apples are there? (2 apples)',
          options: ['1', '2', '3'],
          correctAnswer: '2',
          hint: 'Count the apples carefully.',
          explanation: 'There are 2 apples.',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Perfect! There are 2 apples.',
            incorrect: 'Count again carefully.',
          },
          position: 0,
        },
        {
          id: 'num-s2-2',
          type: 'click',
          question: 'Click the number that matches four stars (4).',
          options: ['3', '4', '5'],
          correctAnswer: '4',
          hint: 'Count each star.',
          explanation: 'There are 4 stars, so the answer is 4.',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Excellent counting! 4 stars = 4.',
            incorrect: 'Count the stars one by one.',
          },
          position: 1,
        },
        {
          id: 'num-s2-3',
          type: 'short_answer',
          question: 'How many books are here? (3 books)',
          correctAnswer: '3',
          hint: 'Count each book.',
          explanation: 'There are 3 books.',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Great! You counted 3 books.',
            incorrect: 'Try counting again: 1, 2, 3.',
          },
          position: 2,
        },
      ],
      order: 1,
    },
    {
      id: 'num-s3',
      lessonId: 'lesson-numbers',
      title: 'Counting forward',
      textContent: 'Say the next number after 1, 2, and 3.',
      audioUrl: '/audio/num-s3-narration.mp3',
      highlights: [
        { phrase: 'next number', emphasisType: 'background', color: '#a5d6a7' },
        { phrase: '1', emphasisType: 'background', color: '#ffd700' },
        { phrase: '2', emphasisType: 'background', color: '#90caf9' },
        { phrase: '3', emphasisType: 'background', color: '#ce93d8' },
      ],
      visuals: [
        { imageUrl: '/visuals/numbers.svg', altText: 'Number sequence 1 2 3', relatedPhrase: 'number', placement: 'inline' },
        { imageUrl: '/visuals/speech.svg', altText: 'Speech bubble for saying numbers', relatedPhrase: 'Say', placement: 'below' },
      ],
      interactions: [
        {
          id: 'num-s3-1',
          type: 'multiple_choice',
          question: 'What number comes after 3?',
          options: ['2', '4', '5'],
          correctAnswer: '4',
          hint: 'Count: 1, 2, 3, and then...',
          explanation: 'After 3 comes 4.',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Perfect! 4 comes after 3.',
            incorrect: 'Count forward: 3, 4.',
          },
          position: 0,
        },
        {
          id: 'num-s3-2',
          type: 'true_false',
          question: 'Does 5 come after 4?',
          correctAnswer: 'True',
          hint: 'Count: 4, 5.',
          explanation: 'Yes, 5 comes right after 4.',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Exactly! 5 follows 4.',
            incorrect: 'Count forward from 4.',
          },
          position: 1,
        },
        {
          id: 'num-s3-3',
          type: 'short_answer',
          question: 'Type the number after 2.',
          correctAnswer: '3',
          hint: 'Count: 1, 2, 3.',
          explanation: 'The number after 2 is 3.',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Excellent! 3 comes after 2.',
            incorrect: 'Try counting: 2, 3.',
          },
          position: 2,
        },
      ],
      order: 2,
    },
  ],

  'lesson-tamil-essentials': [
    {
      id: 'ta-s1',
      lessonId: 'lesson-tamil-essentials',
      title: 'Greetings and thanks',
      titleI18n: {
        english: 'Greetings and thanks',
        tamil: 'வாழ்த்துகள் மற்றும் நன்றி',
        hindi: 'अभिवादन और धन्यवाद',
      },
      textContent: 'Learn “வணக்கம்” (Hello) and “நன்றி” (Thank you).',
      textContentI18n: {
        english: 'Learn “வணக்கம்” (Hello) and “நன்றி” (Thank you).',
        tamil: '“வணக்கம்” (Hello) மற்றும் “நன்றி” (Thank you) கற்றுக்கொள்ளுங்கள்.',
        hindi: '“வணக்கம்” (Hello) और “நன்றி” (Thank you) सीखें।',
      },
      audioUrl: '',
      highlights: [
        { phrase: 'வணக்கம்', emphasisType: 'background', color: '#fde68a' },
        { phrase: 'நன்றி', emphasisType: 'underline', color: 'var(--accent-color)' },
      ],
      visuals: [
        { imageUrl: '/visuals/wave.svg', altText: 'Wave icon', relatedPhrase: 'வணக்கம்', placement: 'inline' },
        { imageUrl: '/visuals/speech.svg', altText: 'Speech icon', relatedPhrase: 'நன்றி', placement: 'below' },
      ],
      interactions: [
        {
          id: 'ta-1',
          type: 'multiple_choice',
          question: 'வணக்கம் means…',
          questionI18n: {
            english: 'வணக்கம் means…',
            tamil: '“வணக்கம்” என்றால்…',
            hindi: '“வணக்கம்” का अर्थ है…',
          },
          questionImageUrl: '/images/greeting-hello.svg',
          questionAudioUrl: '',
          options: ['Hello', 'Thank you', 'Goodbye'],
          optionsI18n: [
            { english: 'Hello', tamil: 'Hello', hindi: 'Hello' },
            { english: 'Thank you', tamil: 'Thank you', hindi: 'Thank you' },
            { english: 'Goodbye', tamil: 'Goodbye', hindi: 'Goodbye' },
          ],
          correctAnswer: 0,
          hint: 'It is used to greet someone.',
          hintI18n: {
            english: 'It is used to greet someone.',
            tamil: 'இது ஒருவரை வாழ்த்த பயன்படுத்தப்படுகிறது.',
            hindi: 'यह किसी को अभिवादन करने के लिए इस्तेमाल होता है।',
          },
          explanation: '“வணக்கம்” is a common Tamil greeting (Hello).',
          explanationI18n: {
            english: '“வணக்கம்” is a common Tamil greeting (Hello).',
            tamil: '“வணக்கம்” என்பது பொதுவான தமிழ் வாழ்த்து (Hello).',
            hindi: '“வணக்கம்” एक सामान्य तमिल अभिवादन है (Hello)।',
          },
          explanationAudioUrl: '',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Great! வணக்கம் = Hello.',
            incorrect: 'Try again. Think: greeting.',
          },
          position: 0,
        },
        {
          id: 'ta-2',
          type: 'multiple_choice',
          question: 'Choose “Thank you” in Tamil.',
          questionI18n: {
            english: 'Choose “Thank you” in Tamil.',
            tamil: 'தமிழில் “Thank you” என்பதைத் தேர்ந்தெடுக்கவும்.',
            hindi: 'तमिल में “Thank you” चुनें।',
          },
          questionImageUrl: '/images/greeting-options.svg',
          questionAudioUrl: '',
          options: ['வணக்கம்', 'நன்றி', 'இல்லை'],
          optionsI18n: [
            { english: 'வணக்கம்', tamil: 'வணக்கம்', hindi: 'वणக்கம்' },
            { english: 'நன்றி', tamil: 'நன்றி', hindi: 'नन्द्री' },
            { english: 'இல்லை', tamil: 'இல்லை', hindi: 'इल्लै' },
          ],
          correctAnswer: 1,
          hint: 'You say it after someone helps you.',
          hintI18n: {
            english: 'You say it after someone helps you.',
            tamil: 'யாராவது உதவிய பிறகு இதை சொல்வீர்கள்.',
            hindi: 'जब कोई आपकी मदद करे, तब आप यह कहते हैं।',
          },
          explanation: 'நன்றி means Thank you.',
          explanationI18n: {
            english: 'நன்றி means Thank you.',
            tamil: 'நன்றி என்றால் Thank you.',
            hindi: 'நன்றி का मतलब Thank you है।',
          },
          explanationAudioUrl: '',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Nice! நன்றி = Thank you.',
            incorrect: 'Good try. Look for the word used for thanks.',
          },
          position: 1,
        },
        {
          id: 'ta-3',
          type: 'true_false',
          question: '“ஆம்” means “Yes”.',
          questionI18n: {
            english: '“ஆம்” means “Yes”.',
            tamil: '“ஆம்” என்றால் “Yes”.',
            hindi: '“ஆம்” का मतलब “Yes” है।',
          },
          questionImageUrl: '/images/responding-greeting.svg',
          questionAudioUrl: '',
          correctAnswer: 'True',
          hint: 'Yes = agree.',
          hintI18n: {
            english: 'Yes = agree.',
            tamil: 'Yes = சம்மதம்.',
            hindi: 'Yes = सहमत होना।',
          },
          explanation: 'ஆம் is used to say Yes.',
          explanationI18n: {
            english: 'ஆம் is used to say Yes.',
            tamil: 'ஆம் என்பது Yes சொல்லப் பயன்படும்.',
            hindi: 'ஆம் का उपयोग Yes कहने के लिए होता है।',
          },
          explanationAudioUrl: '',
          maxAttempts: 2,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Correct!',
            incorrect: 'Try again.',
          },
          position: 2,
        },
      ],
      order: 0,
    },
    {
      id: 'ta-s2',
      lessonId: 'lesson-tamil-essentials',
      title: 'Please and yes/no',
      titleI18n: {
        english: 'Please and yes/no',
        tamil: 'தயவு செய்து மற்றும் ஆம்/இல்லை',
        hindi: 'कृपया और हाँ/नहीं',
      },
      textContent: 'Practice “தயவு செய்து” (Please) and “இல்லை” (No).',
      textContentI18n: {
        english: 'Practice “தயவு செய்து” (Please) and “இல்லை” (No).',
        tamil: '“தயவு செய்து” (Please) மற்றும் “இல்லை” (No) பயிற்சி செய்யுங்கள்.',
        hindi: '“தயவு செய்து” (Please) और “இல்லை” (No) का अभ्यास करें।',
      },
      audioUrl: '',
      highlights: [
        { phrase: 'தயவு செய்து', emphasisType: 'background', color: '#bbf7d0' },
        { phrase: 'இல்லை', emphasisType: 'underline', color: 'var(--accent-color)' },
      ],
      visuals: [
        { imageUrl: '/visuals/speech.svg', altText: 'Speech icon', relatedPhrase: 'தயவு செய்து', placement: 'inline' },
        { imageUrl: '/visuals/wave.svg', altText: 'Wave icon', relatedPhrase: 'வணக்கம்', placement: 'below' },
      ],
      interactions: [
        {
          id: 'ta-4',
          type: 'click',
          question: 'Click the polite word you add when asking for something.',
          questionI18n: {
            english: 'Click the polite word you add when asking for something.',
            tamil: 'எதையாவது கேட்கும்போது மரியாதையாக சேர்க்கும் சொல்லை கிளிக் செய்யவும்.',
            hindi: 'कुछ माँगते समय जो विनम्र शब्द जोड़ते हैं, उसे चुनें।',
          },
          questionImageUrl: '/images/asking-question.svg',
          questionAudioUrl: '',
          options: ['தயவு செய்து', 'நன்றி', 'பிரியாவிடை'],
          optionsI18n: [
            { english: 'தயவு செய்து', tamil: 'தயவு செய்து', hindi: 'कृपया' },
            { english: 'நன்றி', tamil: 'நன்றி', hindi: 'धन्यवाद' },
            { english: 'பிரியாவிடை', tamil: 'பிரியாவிடை', hindi: 'अलविदा' },
          ],
          correctAnswer: 0,
          hint: 'It is like “Please”.',
          hintI18n: {
            english: 'It is like “Please”.',
            tamil: 'இது “Please” போல.',
            hindi: 'यह “Please” जैसा है।',
          },
          explanation: 'தயவு செய்து is used to say Please.',
          explanationI18n: {
            english: 'தயவு செய்து is used to say Please.',
            tamil: 'தயவு செய்து என்பது Please சொல்லப் பயன்படும்.',
            hindi: 'தயவு செய்து का उपयोग Please कहने के लिए होता है।',
          },
          explanationAudioUrl: '',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Well done!',
            incorrect: 'Try again. Pick the polite request word.',
          },
          position: 0,
        },
        {
          id: 'ta-5',
          type: 'multiple_choice',
          question: 'Which one means “No” in Tamil?',
          questionI18n: {
            english: 'Which one means “No” in Tamil?',
            tamil: 'தமிழில் “No” என்றால் எது?',
            hindi: 'तमिल में “No” कौन सा है?',
          },
          questionImageUrl: '/images/type-greeting.svg',
          questionAudioUrl: '',
          options: ['ஆம்', 'இல்லை', 'நன்றி'],
          optionsI18n: [
            { english: 'ஆம்', tamil: 'ஆம்', hindi: 'हाँ' },
            { english: 'இல்லை', tamil: 'இல்லை', hindi: 'नहीं' },
            { english: 'நன்றி', tamil: 'நன்றி', hindi: 'धन्यवाद' },
          ],
          correctAnswer: 1,
          hint: 'Not yes.',
          hintI18n: {
            english: 'Not yes.',
            tamil: 'ஆம் அல்ல.',
            hindi: 'हाँ नहीं।',
          },
          explanation: 'இல்லை is used to say No.',
          explanationI18n: {
            english: 'இல்லை is used to say No.',
            tamil: 'இல்லை என்பது No சொல்லப் பயன்படும்.',
            hindi: 'इल्लै का उपयोग No कहने के लिए होता है।',
          },
          explanationAudioUrl: '',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Correct! இல்லை = No.',
            incorrect: 'Almost. Look for the opposite of ஆம்.',
          },
          position: 1,
        },
        {
          id: 'ta-6',
          type: 'multiple_choice',
          question: 'Pick a greeting you can use any time.',
          questionI18n: {
            english: 'Pick a greeting you can use any time.',
            tamil: 'எப்போது வேண்டுமானாலும் பயன்படுத்தக்கூடிய வாழ்த்தைத் தேர்ந்தெடுக்கவும்.',
            hindi: 'ऐसा अभिवादन चुनें जो आप कभी भी कह सकते हैं।',
          },
          questionImageUrl: '/images/greeting-options.svg',
          questionAudioUrl: '',
          options: ['வணக்கம்', 'பிரியாவிடை', 'நன்றி'],
          optionsI18n: [
            { english: 'வணக்கம்', tamil: 'வணக்கம்', hindi: 'नमस्ते' },
            { english: 'பிரியாவிடை', tamil: 'பிரியாவிடை', hindi: 'अलविदा' },
            { english: 'நன்றி', tamil: 'நன்றி', hindi: 'धन्यवाद' },
          ],
          correctAnswer: 0,
          hint: 'It is “Hello”.',
          hintI18n: {
            english: 'It is “Hello”.',
            tamil: 'இது “Hello”.',
            hindi: 'यह “Hello” है।',
          },
          explanation: 'வணக்கம் is a general greeting.',
          explanationI18n: {
            english: 'வணக்கம் is a general greeting.',
            tamil: 'வணக்கம் என்பது பொதுவான வாழ்த்து.',
            hindi: 'वணக்கம் एक सामान्य अभिवादन है।',
          },
          explanationAudioUrl: '',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Great greeting choice!',
            incorrect: 'Try again. Pick the greeting word.',
          },
          position: 2,
        },
      ],
      order: 1,
    },
  ],

  'lesson-hindi-essentials': [
    {
      id: 'hi-s1',
      lessonId: 'lesson-hindi-essentials',
      title: 'Greetings and thanks',
      titleI18n: {
        english: 'Greetings and thanks',
        tamil: 'வாழ்த்துகள் மற்றும் நன்றி',
        hindi: 'अभिवादन और धन्यवाद',
      },
      textContent: 'Learn “नमस्ते” (Hello) and “धन्यवाद” (Thank you).',
      textContentI18n: {
        english: 'Learn “नमस्ते” (Hello) and “धन्यवाद” (Thank you).',
        tamil: '“नमस्ते” (Hello) மற்றும் “धन्यवाद” (Thank you) கற்றுக்கொள்ளுங்கள்.',
        hindi: '“नमस्ते” (Hello) और “धन्यवाद” (Thank you) सीखें।',
      },
      audioUrl: '',
      highlights: [
        { phrase: 'नमस्ते', emphasisType: 'background', color: '#ddd6fe' },
        { phrase: 'धन्यवाद', emphasisType: 'underline', color: 'var(--accent-color)' },
      ],
      visuals: [
        { imageUrl: '/visuals/hello.svg', altText: 'Hello icon', relatedPhrase: 'नमस्ते', placement: 'inline' },
        { imageUrl: '/visuals/speech.svg', altText: 'Speech icon', relatedPhrase: 'धन्यवाद', placement: 'below' },
      ],
      interactions: [
        {
          id: 'hi-1',
          type: 'multiple_choice',
          question: 'नमस्ते means…',
          questionI18n: {
            english: 'नमस्ते means…',
            tamil: '“नमस्ते” என்றால்…',
            hindi: '“नमस्ते” का अर्थ है…',
          },
          questionImageUrl: '/images/greeting-hello.svg',
          questionAudioUrl: '',
          options: ['Hello', 'Thank you', 'Good night'],
          optionsI18n: [
            { english: 'Hello', tamil: 'Hello', hindi: 'Hello' },
            { english: 'Thank you', tamil: 'Thank you', hindi: 'Thank you' },
            { english: 'Good night', tamil: 'Good night', hindi: 'Good night' },
          ],
          correctAnswer: 0,
          hint: 'It is used to greet someone.',
          hintI18n: {
            english: 'It is used to greet someone.',
            tamil: 'இது ஒருவரை வாழ்த்த பயன்படுத்தப்படுகிறது.',
            hindi: 'यह अभिवादन करने के लिए उपयोग होता है।',
          },
          explanation: 'नमस्ते is a common Hindi greeting (Hello).',
          explanationI18n: {
            english: 'नमस्ते is a common Hindi greeting (Hello).',
            tamil: 'नमस्ते என்பது பொதுவான இந்தி வாழ்த்து (Hello).',
            hindi: 'नमस्ते एक सामान्य हिंदी अभिवादन है (Hello)।',
          },
          explanationAudioUrl: '',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Great! नमस्ते = Hello.',
            incorrect: 'Try again. Think: greeting.',
          },
          position: 0,
        },
        {
          id: 'hi-2',
          type: 'multiple_choice',
          question: 'Choose “Thank you” in Hindi.',
          questionI18n: {
            english: 'Choose “Thank you” in Hindi.',
            tamil: 'இந்தியில் “Thank you” என்பதைத் தேர்ந்தெடுக்கவும்.',
            hindi: 'हिंदी में “Thank you” चुनें।',
          },
          questionImageUrl: '/images/greeting-options.svg',
          questionAudioUrl: '',
          options: ['धन्यवाद', 'नमस्ते', 'नहीं'],
          optionsI18n: [
            { english: 'धन्यवाद', tamil: 'धन्यवाद', hindi: 'धन्यवाद' },
            { english: 'नमस्ते', tamil: 'नमस्ते', hindi: 'नमस्ते' },
            { english: 'नहीं', tamil: 'नहीं', hindi: 'नहीं' },
          ],
          correctAnswer: 0,
          hint: 'You say it after someone helps you.',
          hintI18n: {
            english: 'You say it after someone helps you.',
            tamil: 'யாராவது உதவிய பிறகு இதை சொல்வீர்கள்.',
            hindi: 'जब कोई आपकी मदद करे, तब आप यह कहते हैं।',
          },
          explanation: 'धन्यवाद means Thank you.',
          explanationI18n: {
            english: 'धन्यवाद means Thank you.',
            tamil: 'धन्यवाद என்றால் Thank you.',
            hindi: 'धन्यवाद का मतलब Thank you है।',
          },
          explanationAudioUrl: '',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Nice! धन्यवाद = Thank you.',
            incorrect: 'Good try. Pick the word used for thanks.',
          },
          position: 1,
        },
        {
          id: 'hi-3',
          type: 'true_false',
          question: '“हाँ” means “Yes”.',
          questionI18n: {
            english: '“हाँ” means “Yes”.',
            tamil: '“हाँ” என்றால் “Yes”.',
            hindi: '“हाँ” का मतलब “Yes” है।',
          },
          questionImageUrl: '/images/responding-greeting.svg',
          questionAudioUrl: '',
          correctAnswer: 'True',
          hint: 'Yes = agree.',
          hintI18n: {
            english: 'Yes = agree.',
            tamil: 'Yes = சம்மதம்.',
            hindi: 'Yes = सहमत होना।',
          },
          explanation: 'हाँ is used to say Yes.',
          explanationI18n: {
            english: 'हाँ is used to say Yes.',
            tamil: 'हाँ என்பது Yes சொல்லப் பயன்படும்.',
            hindi: 'हाँ का उपयोग Yes कहने के लिए होता है।',
          },
          explanationAudioUrl: '',
          maxAttempts: 2,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Correct!',
            incorrect: 'Try again.',
          },
          position: 2,
        },
      ],
      order: 0,
    },
    {
      id: 'hi-s2',
      lessonId: 'lesson-hindi-essentials',
      title: 'Please and yes/no',
      titleI18n: {
        english: 'Please and yes/no',
        tamil: 'கृपया மற்றும் ஹா/நஹீ',
        hindi: 'कृपया और हाँ/नहीं',
      },
      textContent: 'Practice “कृपया” (Please) and “नहीं” (No).',
      textContentI18n: {
        english: 'Practice “कृपया” (Please) and “नहीं” (No).',
        tamil: '“कृपया” (Please) மற்றும் “नहीं” (No) பயிற்சி செய்யுங்கள்.',
        hindi: '“कृपया” (Please) और “नहीं” (No) का अभ्यास करें।',
      },
      audioUrl: '',
      highlights: [
        { phrase: 'कृपया', emphasisType: 'background', color: '#bbf7d0' },
        { phrase: 'नहीं', emphasisType: 'underline', color: 'var(--accent-color)' },
      ],
      visuals: [
        { imageUrl: '/visuals/speech.svg', altText: 'Speech icon', relatedPhrase: 'कृपया', placement: 'inline' },
        { imageUrl: '/visuals/hello.svg', altText: 'Hello icon', relatedPhrase: 'नमस्ते', placement: 'below' },
      ],
      interactions: [
        {
          id: 'hi-4',
          type: 'click',
          question: 'Click the polite word you add when asking for something.',
          questionI18n: {
            english: 'Click the polite word you add when asking for something.',
            tamil: 'எதையாவது கேட்கும்போது மரியாதையாக சேர்க்கும் சொல்லை கிளிக் செய்யவும்.',
            hindi: 'कुछ माँगते समय जो विनम्र शब्द जोड़ते हैं, उसे चुनें।',
          },
          questionImageUrl: '/images/asking-question.svg',
          questionAudioUrl: '',
          options: ['कृपया', 'धन्यवाद', 'अलविदा'],
          optionsI18n: [
            { english: 'कृपया', tamil: 'कृपया', hindi: 'कृपया' },
            { english: 'धन्यवाद', tamil: 'धन्यवाद', hindi: 'धन्यवाद' },
            { english: 'अलविदा', tamil: 'அலவிதா', hindi: 'अलविदा' },
          ],
          correctAnswer: 0,
          hint: 'It is like “Please”.',
          hintI18n: {
            english: 'It is like “Please”.',
            tamil: 'இது “Please” போல.',
            hindi: 'यह “Please” जैसा है।',
          },
          explanation: 'कृपया is used to say Please.',
          explanationI18n: {
            english: 'कृपया is used to say Please.',
            tamil: 'कृपया என்பது Please சொல்லப் பயன்படும்.',
            hindi: 'कृपया का उपयोग Please कहने के लिए होता है।',
          },
          explanationAudioUrl: '',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Well done!',
            incorrect: 'Try again. Pick the polite request word.',
          },
          position: 0,
        },
        {
          id: 'hi-5',
          type: 'multiple_choice',
          question: 'Which one means “No” in Hindi?',
          questionI18n: {
            english: 'Which one means “No” in Hindi?',
            tamil: 'இந்தியில் “No” என்றால் எது?',
            hindi: 'हिंदी में “No” कौन सा है?',
          },
          questionImageUrl: '/images/type-greeting.svg',
          questionAudioUrl: '',
          options: ['हाँ', 'नहीं', 'धन्यवाद'],
          optionsI18n: [
            { english: 'हाँ', tamil: 'हाँ', hindi: 'हाँ' },
            { english: 'नहीं', tamil: 'नहीं', hindi: 'नहीं' },
            { english: 'धन्यवाद', tamil: 'धन्यवाद', hindi: 'धन्यवाद' },
          ],
          correctAnswer: 1,
          hint: 'Not yes.',
          hintI18n: {
            english: 'Not yes.',
            tamil: 'ஆம் அல்ல.',
            hindi: 'हाँ नहीं।',
          },
          explanation: 'नहीं is used to say No.',
          explanationI18n: {
            english: 'नहीं is used to say No.',
            tamil: 'नहीं என்பது No சொல்லப் பயன்படும்.',
            hindi: 'नहीं का उपयोग No कहने के लिए होता है।',
          },
          explanationAudioUrl: '',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Correct! नहीं = No.',
            incorrect: 'Almost. Look for the opposite of हाँ.',
          },
          position: 1,
        },
        {
          id: 'hi-6',
          type: 'multiple_choice',
          question: 'Pick a greeting you can use any time.',
          questionI18n: {
            english: 'Pick a greeting you can use any time.',
            tamil: 'எப்போது வேண்டுமானாலும் பயன்படுத்தக்கூடிய வாழ்த்தைத் தேர்ந்தெடுக்கவும்.',
            hindi: 'ऐसा अभिवादन चुनें जो आप कभी भी कह सकते हैं।',
          },
          questionImageUrl: '/images/greeting-options.svg',
          questionAudioUrl: '',
          options: ['नमस्ते', 'अलविदा', 'धन्यवाद'],
          optionsI18n: [
            { english: 'नमस्ते', tamil: 'नमस्ते', hindi: 'नमस्ते' },
            { english: 'अलविदा', tamil: 'அலவிதா', hindi: 'अलविदा' },
            { english: 'धन्यवाद', tamil: 'धन्यवाद', hindi: 'धन्यवाद' },
          ],
          correctAnswer: 0,
          hint: 'It is “Hello”.',
          hintI18n: {
            english: 'It is “Hello”.',
            tamil: 'இது “Hello”.',
            hindi: 'यह “Hello” है।',
          },
          explanation: 'नमस्ते is a general greeting.',
          explanationI18n: {
            english: 'नमस्ते is a general greeting.',
            tamil: 'नमस्ते என்பது பொதுவான வாழ்த்து.',
            hindi: 'नमस्ते एक सामान्य अभिवादन है।',
          },
          explanationAudioUrl: '',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Great greeting choice!',
            incorrect: 'Try again. Pick the greeting word.',
          },
          position: 2,
        },
      ],
      order: 1,
    },
  ],
};

export default { ...lessonSectionSamples, ...lessonSectionSamplesHindi, ...lessonSectionSamplesTamil };
