/**
 * sectionSamplesTamil.js
 *
 * Static section data for Tamil language lessons.
 * Each lesson has 2–3 sections mirroring the English sectionSamples structure.
 */

const lessonSectionSamplesTamil = {
  'lesson-greetings-tamil': [
    {
      id: 'greet-ta-s1',
      lessonId: 'lesson-greetings-tamil',
      title: 'வாழ்த்தின் அடிப்படை',
      titleI18n: {
        english: 'Greeting basics',
        tamil: 'வாழ்த்தின் அடிப்படை',
        hindi: 'अभिवादन की मूल बातें',
      },
      textContent: 'வணக்கம்! இந்த பகுதி தமிழில் மரியாதையுடன் எப்படி வாழ்த்துவது என்பதை காட்டுகிறது.',
      textContentI18n: {
        english: 'Vanakkam! This section shows how to greet politely in Tamil.',
        tamil: 'வணக்கம்! இந்த பகுதி தமிழில் மரியாதையுடன் எப்படி வாழ்த்துவது என்பதை காட்டுகிறது.',
        hindi: 'वणक्कम! यह भाग तमिल में शिष्ट तरीके से अभिवादन करना दिखाता है।',
      },
      audioUrl: '/audio/greet-ta-s1-narration.mp3',
      highlights: [
        { phrase: 'வணக்கம்', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'வாழ்த்து', emphasisType: 'underline', color: 'var(--accent-color)' },
        { phrase: 'மரியாதை', emphasisType: 'bold' },
      ],
      visuals: [
        { imageUrl: '/visuals/hello.svg', altText: 'Waving hand saying vanakkam', relatedPhrase: 'வணக்கம்', placement: 'inline' },
        { imageUrl: '/visuals/how-are-you.svg', altText: 'People greeting politely', relatedPhrase: 'மரியாதை வாழ்த்து', placement: 'below' },
      ],
      interactions: [
        {
          id: 'greet-ta-1',
          type: 'true_false',
          question: '"வணக்கம்" என்பது நட்பான வாழ்த்தா?',
          questionI18n: { english: 'Is "வணக்கம்" (Vanakkam) a friendly greeting?', tamil: '"வணக்கம்" என்பது நட்பான வாழ்த்தா?', hindi: 'क्या "வணக்கம்" (Vanakkam) एक दोस्ताना अभिवादन है?' },
          correctAnswer: 'True',
          hint: 'இது தமிழில் மிகவும் பொதுவான வாழ்த்து.',
          hintI18n: { english: 'This is the most common greeting in Tamil.', tamil: 'இது தமிழில் மிகவும் பொதுவான வாழ்த்து.', hindi: 'यह तमिल में सबसे आम अभिवादन है।' },
          explanation: '"வணக்கம்" என்பது ஒருவரை வாழ்த்தப் பயன்படும் பொதுவான சொல்.',
          explanationI18n: { english: '"Vanakkam" is a common, friendly way to greet someone.', tamil: '"வணக்கம்" என்பது ஒருவரை வாழ்த்தப் பயன்படும் பொதுவான சொல்.', hindi: '"वणக்கम" किसी का अभिवादन करने का सामान्य और दोस्ताना तरीका है।' },
          maxAttempts: 3, timeLimitSeconds: 25,
          feedback: { correct: 'சிறப்பு! "வணக்கம்" நட்பான வாழ்த்து.', incorrect: 'நல்ல முயற்சி. மீண்டும் முயற்சிப்போம்.' },
          position: 0,
        },
        {
          id: 'greet-ta-2',
          type: 'multiple_choice',
          question: 'நட்பான வாழ்த்தைத் தேர்ந்தெடுக்கவும்.',
          questionI18n: { english: 'Choose a friendly greeting.', tamil: 'நட்பான வாழ்த்தைத் தேர்ந்தெடுக்கவும்.', hindi: 'एक दोस्ताना अभिवादन चुनें।' },
          options: ['வணக்கம்', 'பிரியாவிடை', 'பின்னர்'],
          optionsI18n: [
            { english: 'Vanakkam (Hello)', tamil: 'வணக்கம்', hindi: 'वणक्कम (नमस्ते)' },
            { english: 'Goodbye', tamil: 'பிரியாவிடை', hindi: 'अलविदा' },
            { english: 'Later', tamil: 'பின்னர்', hindi: 'बाद में' },
          ],
          correctAnswer: 0,
          hint: 'உரையாடலை தொடங்கும்போது சொல்லும் சொல்.',
          explanation: '"வணக்கம்" நட்பான வாழ்த்து.',
          maxAttempts: 3, timeLimitSeconds: 25,
          feedback: { correct: 'ஆம்! "வணக்கம்" நட்பான வாழ்த்து.', incorrect: 'தொடக்கத்தில் பயன்படுத்தும் வாழ்த்தைத் தேர்வுசெய்யவும்.' },
          position: 1,
        },
        {
          id: 'greet-ta-3',
          type: 'click',
          question: 'ஒருவரின் நலன் கேட்கும் தமிழ் வாக்கியத்தை கிளிக் செய்யவும்.',
          questionI18n: { english: 'Click the Tamil phrase to ask about someone.', tamil: 'ஒருவரின் நலன் கேட்கும் தமிழ் வாக்கியத்தை கிளிக் செய்யவும்.', hindi: 'किसी का हाल-चाल पूछने वाला तमिल वाक्य चुनें।' },
          options: ['நீங்கள் எப்படி இருக்கிறீர்கள்?', 'அது எங்கே?', 'பின்னர் சந்திப்போம்'],
          optionsI18n: [
            { english: 'How are you?', tamil: 'நீங்கள் எப்படி இருக்கிறீர்கள்?', hindi: 'आप कैसे हैं?' },
            { english: 'Where is it?', tamil: 'அது எங்கே?', hindi: 'यह कहाँ है?' },
            { english: 'See you later', tamil: 'பின்னர் சந்திப்போம்', hindi: 'फिर मिलेंगे' },
          ],
          correctAnswer: 0,
          hint: 'இது உணர்வுகள்/நலன் பற்றிய கேள்வி.',
          explanation: '"நீங்கள் எப்படி இருக்கிறீர்கள்?" நலன் கேட்கப் பயன்படும்.',
          maxAttempts: 3, timeLimitSeconds: 30,
          feedback: { correct: 'சிறப்பு! நலன் கேட்கும் கேள்வி.', incorrect: 'நலன் பற்றிய கேள்வியை முயற்சிக்கவும்.' },
          position: 2,
        },
      ],
      order: 0,
    },
    {
      id: 'greet-ta-s2',
      lessonId: 'lesson-greetings-tamil',
      title: 'நட்பான சொற்றொடர்கள்',
      titleI18n: {
        english: 'Friendly phrases',
        tamil: 'நட்பான சொற்றொடர்கள்',
        hindi: 'दोस्ताना वाक्य',
      },
      textContent: 'சிரிப்புடன் "வணக்கம்" அல்லது "ஹலோ" சொல்லுங்கள். "நீங்கள் எப்படி இருக்கிறீர்கள்?" என்று கேளுங்கள்.',
      textContentI18n: {
        english: 'Say "Vanakkam" or "Hello" with a smile. Ask "Neengal eppadi irukkeergal?"',
        tamil: 'சிரிப்புடன் "வணக்கம்" அல்லது "ஹலோ" சொல்லுங்கள். "நீங்கள் எப்படி இருக்கிறீர்கள்?" என்று கேளுங்கள்.',
        hindi: 'मुस्कान के साथ "வணக்கம்" या "ஹலோ" कहें। "நீங்கள் எப்படி இருக்கிறீர்கள்?" पूछें।',
      },
      audioUrl: '/audio/greet-ta-s2-narration.mp3',
      highlights: [
        { phrase: 'வணக்கம்', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'ஹலோ', emphasisType: 'background', color: '#90caf9' },
        { phrase: 'சிரிப்பு', emphasisType: 'underline', color: '#f06292' },
        { phrase: 'நீங்கள் எப்படி இருக்கிறீர்கள்?', emphasisType: 'background', color: '#a5d6a7' },
      ],
      visuals: [
        { imageUrl: '/visuals/hello.svg', altText: 'Friendly wave', relatedPhrase: 'வணக்கம்', placement: 'inline' },
        { imageUrl: '/visuals/how-are-you.svg', altText: 'Friendly question', relatedPhrase: 'நீங்கள் எப்படி இருக்கிறீர்கள்?', placement: 'below' },
      ],
      interactions: [
        {
          id: 'greet-ta-s2-1',
          type: 'multiple_choice',
          question: '"வணக்கம்" சொல்லும் நட்பான வழி எது?',
          questionI18n: { english: 'What is a friendly way to say hello in Tamil?', tamil: '"வணக்கம்" சொல்லும் நட்பான வழி எது?', hindi: 'तमिल में "வணக்கம்" कहने का दोस्ताना तरीका कौन सा है?' },
          options: ['ஹலோ!', 'போகுங்கள்!', 'இப்போது இல்லை.'],
          optionsI18n: [
            { english: 'Hello!', tamil: 'ஹலோ!', hindi: 'हलो!' },
            { english: 'Go away!', tamil: 'போகுங்கள்!', hindi: 'चले जाओ!' },
            { english: 'Not now.', tamil: 'இப்போது இல்லை.', hindi: 'अभी नहीं।' },
          ],
          correctAnswer: 0,
          hint: 'சூடான மற்றும் வரவேற்கும் சொல்லை தேர்ந்தெடுங்கள்.',
          explanation: '"ஹலோ!" நட்பான மற்றும் எளிய வாழ்த்து.',
          maxAttempts: 3, timeLimitSeconds: 25,
          feedback: { correct: 'சரியாக! "ஹலோ!" மிகவும் நட்பானது.', incorrect: 'மீண்டும் முயற்சிக்கவும். சூடான வாழ்த்தைத் தேர்வுசெய்யவும்.' },
          position: 0,
        },
        {
          id: 'greet-ta-s2-2',
          type: 'true_false',
          question: 'ஒருவரை வாழ்த்தும்போது சிரிக்க வேண்டுமா?',
          questionI18n: { english: 'Should you smile when greeting someone?', tamil: 'ஒருவரை வாழ்த்தும்போது சிரிக்க வேண்டுமா?', hindi: 'क्या किसी का अभिवादन करते समय मुस्कुराना चाहिए?' },
          correctAnswer: 'True',
          hint: 'சிரிப்பு மக்களை வரவேற்கும் உணர்வை தருகிறது.',
          explanation: 'வாழ்த்தும்போது சிரிப்பது நட்பாகவும் அணுகக்கூடியதாகவும் காட்டுகிறது.',
          maxAttempts: 3, timeLimitSeconds: 25,
          feedback: { correct: 'சரியாக! சிரிப்பு வாழ்த்தை சூடாக்குகிறது.', incorrect: 'மக்களை வரவேற்கும் உணர்வு என்ன என்று நினைத்துப் பாருங்கள்.' },
          position: 1,
        },
        {
          id: 'greet-ta-s2-3',
          type: 'short_answer',
          question: 'ஒருவரிடம் கேட்கக்கூடிய நட்பான தமிழ் கேள்வியை டைப் செய்யவும்.',
          questionI18n: { english: 'Type a friendly Tamil question you can ask someone.', tamil: 'ஒருவரிடம் கேட்கக்கூடிய நட்பான தமிழ் கேள்வியை டைப் செய்யவும்.', hindi: 'किसी से पूछने के लिए एक दोस्ताना तमिल सवाल टाइप करें।' },
          correctAnswer: 'நீங்கள் எப்படி இருக்கிறீர்கள்',
          correctAnswerI18n: { english: 'How are you', tamil: 'நீங்கள் எப்படி இருக்கிறீர்கள்', hindi: 'आप कैसे हैं' },
          hint: 'அவர்களின் நலன் பற்றி கேளுங்கள்.',
          explanation: '"நீங்கள் எப்படி இருக்கிறீர்கள்?" நீங்கள் அவர்களைப் பற்றி அக்கறை கொள்வதைக் காட்டுகிறது.',
          maxAttempts: 3, timeLimitSeconds: 35,
          feedback: { correct: 'நல்ல கேள்வி! மிகவும் நட்பானது.', incorrect: '"நீங்கள் எப்படி இருக்கிறீர்கள்?" என்று கேட்டுப் பாருங்கள்.' },
          position: 2,
        },
      ],
      order: 1,
    },
  ],

  'lesson-vocabulary-tamil': [
    {
      id: 'vocab-ta-s1',
      lessonId: 'lesson-vocabulary-tamil',
      title: 'அன்றாட பொருட்கள்',
      titleI18n: { english: 'Everyday objects', tamil: 'அன்றாட பொருட்கள்', hindi: 'रोज़मर्रा की वस्तुएँ' },
      textContent: 'அன்றாட பொருட்களுக்கான எளிய தமிழ் சொற்களை கற்றுக்கொள்வோம்.',
      textContentI18n: { english: 'Let\'s learn simple Tamil words for everyday items.', tamil: 'அன்றாட பொருட்களுக்கான எளிய தமிழ் சொற்களை கற்றுக்கொள்வோம்.', hindi: 'आइए रोज़मर्रा की चीज़ों के लिए सरल तमिल शब्द सीखें।' },
      audioUrl: '/audio/vocab-ta-s1-narration.mp3',
      highlights: [
        { phrase: 'எளிய சொற்கள்', emphasisType: 'background', color: '#b39ddb' },
        { phrase: 'அன்றாட', emphasisType: 'underline', color: 'var(--accent-color)' },
      ],
      visuals: [{ imageUrl: '/visuals/basic-words.svg', altText: 'Everyday objects', relatedPhrase: 'அன்றாட', placement: 'inline' }],
      interactions: [
        { id: 'vocab-ta-1', type: 'multiple_choice', question: 'உட்காரக்கூடிய பொருளின் தமிழ் சொல்?', options: ['நாற்காலி', 'ஆப்பிள்', 'மழை'], correctAnswer: 0, hint: 'உட்கார பயன்படும் பொருள்.', explanation: 'நாற்காலி = Chair', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'ஆம்! நாற்காலியில் உட்காரலாம்.', incorrect: 'உட்கார பயன்படும் பொருளைத் தேர்வுசெய்யவும்.' }, position: 0 },
        { id: 'vocab-ta-2', type: 'multiple_choice', question: 'சாப்பிடக்கூடிய பொருளின் தமிழ் சொல்?', options: ['ஆப்பிள்', 'நாற்காலி', 'புத்தகம்'], correctAnswer: 0, hint: 'இது ஒரு பழம்.', explanation: 'ஆப்பிள் = Apple', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'சரி! ஆப்பிள் சாப்பிடலாம்.', incorrect: 'பழத்தைத் தேர்வுசெய்யவும்.' }, position: 1 },
        { id: 'vocab-ta-3', type: 'click', question: 'படிக்கக்கூடிய பொருளின் தமிழ் சொல்லை கிளிக் செய்யவும்.', options: ['புத்தகம்', 'மேகம்', 'செருப்பு'], correctAnswer: 0, hint: 'இதில் வார்த்தைகள் உள்ளன.', explanation: 'புத்தகம் = Book', maxAttempts: 3, timeLimitSeconds: 30, feedback: { correct: 'சிறப்பு! புத்தகம் படிப்பதற்கு.', incorrect: 'படிக்கக்கூடிய பொருளை முயற்சிக்கவும்.' }, position: 2 },
        { id: 'vocab-ta-4', type: 'short_answer', question: 'வாழும் இடத்தின் தமிழ் சொல் டைப் செய்யவும்.', correctAnswer: 'வீடு', hint: 'தூங்கும் இடத்தை நினைத்துப் பாருங்கள்.', explanation: 'வீடு = Home', maxAttempts: 3, timeLimitSeconds: 35, feedback: { correct: 'அருமை!', incorrect: '"வீடு" டைப் செய்யவும்.' }, position: 3 },
      ],
      order: 0,
    },
    {
      id: 'vocab-ta-s2',
      lessonId: 'lesson-vocabulary-tamil',
      title: 'மக்கள் மற்றும் இடங்கள்',
      titleI18n: { english: 'People and places', tamil: 'மக்கள் மற்றும் இடங்கள்', hindi: 'लोग और स्थान' },
      textContent: 'தினமும் பார்க்கும் மக்கள் மற்றும் இடங்களுக்கான தமிழ் சொற்களை பயிற்சி செய்யுங்கள்.',
      textContentI18n: { english: 'Practice Tamil words for people and places you see daily.', tamil: 'தினமும் பார்க்கும் மக்கள் மற்றும் இடங்களுக்கான தமிழ் சொற்களை பயிற்சி செய்யுங்கள்.', hindi: 'रोज़ाना दिखने वाले लोगों और जगहों के तमिल शब्दों का अभ्यास करें।' },
      audioUrl: '/audio/vocab-ta-s2-narration.mp3',
      highlights: [
        { phrase: 'மக்கள்', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'இடங்கள்', emphasisType: 'background', color: '#90caf9' },
      ],
      visuals: [{ imageUrl: '/visuals/sun.svg', altText: 'Daily life', relatedPhrase: 'தினமும்', placement: 'inline' }],
      interactions: [
        { id: 'vocab-ta-s2-1', type: 'multiple_choice', question: 'உணவு வாங்க எங்கே செல்வீர்கள்?', options: ['கடை', 'வானம்', 'மரம்'], correctAnswer: 0, hint: 'அங்கே பொருட்கள் வாங்குவார்கள்.', explanation: 'கடை = Store — பொருட்கள் வாங்கும் இடம்.', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'ஆம்! கடையில் உணவு வாங்கலாம்.', incorrect: 'பொருட்கள் வாங்கும் இடத்தை நினைத்துப் பாருங்கள்.' }, position: 0 },
        { id: 'vocab-ta-s2-2', type: 'click', question: 'கற்பிக்கும் நபரின் தமிழ் சொல்லை கிளிக் செய்யவும்.', options: ['ஆசிரியர்', 'இலை', 'கதவு'], correctAnswer: 0, hint: 'இவர் உங்களுக்கு கற்றுக் கொடுப்பார்.', explanation: 'ஆசிரியர் = Teacher', maxAttempts: 3, timeLimitSeconds: 30, feedback: { correct: 'சரியாக! ஆசிரியர் கற்பிப்பார்.', incorrect: 'கற்பிக்கும் நபரின் சொல்லை முயற்சிக்கவும்.' }, position: 1 },
        { id: 'vocab-ta-s2-3', type: 'short_answer', question: 'குடும்பத்தில் ஒருவரின் தமிழ் சொல் டைப் செய்யவும்.', correctAnswer: 'அம்மா', hint: 'அம்மா, அப்பா, அக்கா நினைத்துப் பாருங்கள்.', explanation: 'குடும்ப உறுப்பினர்கள்: அம்மா, அப்பா, அக்கா, அண்ணா.', maxAttempts: 3, timeLimitSeconds: 35, feedback: { correct: 'அருமை! குடும்ப உறுப்பினர்.', incorrect: '"அம்மா", "அப்பா", அல்லது "அக்கா" போன்ற சொற்களை முயற்சிக்கவும்.' }, position: 2 },
      ],
      order: 1,
    },
    {
      id: 'vocab-ta-s3',
      lessonId: 'lesson-vocabulary-tamil',
      title: 'செயல் சொற்கள்',
      titleI18n: { english: 'Action words', tamil: 'செயல் சொற்கள்', hindi: 'क्रिया शब्द' },
      textContent: 'எளிய தமிழ் செயல் சொற்களை கற்றுக்கொள்ளுங்கள்: "சாப்பிடு", "நடை", "படி".',
      textContentI18n: { english: 'Learn simple Tamil action words like "saappidu", "nadai", and "padi".', tamil: 'எளிய தமிழ் செயல் சொற்களை கற்றுக்கொள்ளுங்கள்: "சாப்பிடு", "நடை", "படி".', hindi: 'सरल तमिल क्रिया शब्द सीखें: "साप्पिडु", "नडै", "पडि".' },
      audioUrl: '/audio/vocab-ta-s3-narration.mp3',
      highlights: [
        { phrase: 'செயல் சொற்கள்', emphasisType: 'background', color: '#a5d6a7' },
        { phrase: 'சாப்பிடு', emphasisType: 'background', color: '#ffab91' },
        { phrase: 'நடை', emphasisType: 'background', color: '#90caf9' },
        { phrase: 'படி', emphasisType: 'background', color: '#ce93d8' },
      ],
      visuals: [{ imageUrl: '/visuals/speech.svg', altText: 'Speaking action words', relatedPhrase: 'சொல்லுங்கள்', placement: 'below' }],
      interactions: [
        { id: 'vocab-ta-s3-1', type: 'multiple_choice', question: 'உணவுடன் என்ன செய்வீர்கள்?', options: ['சாப்பிடு', 'பறக்கு', 'தூங்கு'], correctAnswer: 0, hint: 'பசிக்கும்போது இதை செய்வீர்கள்.', explanation: 'சாப்பிடு = Eat', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'சரி! உணவை சாப்பிடுவோம்.', incorrect: 'உணவுடன் என்ன செய்வீர்கள் என்று நினைத்துப் பாருங்கள்.' }, position: 0 },
        { id: 'vocab-ta-s3-2', type: 'click', question: 'கால்களால் செய்யும் செயலை கிளிக் செய்யவும்.', options: ['நடை', 'நினை', 'பாடு'], correctAnswer: 0, hint: 'ஒரு இடத்தில் இருந்து மற்றொரு இடத்திற்கு செல்வது.', explanation: 'நடை = Walk', maxAttempts: 3, timeLimitSeconds: 30, feedback: { correct: 'ஆம்! கால்களால் நடப்போம்.', incorrect: 'கால்களால் செய்யும் செயலை முயற்சிக்கவும்.' }, position: 1 },
        { id: 'vocab-ta-s3-3', type: 'short_answer', question: 'புத்தகத்துடன் செய்யும் செயலை தமிழில் டைப் செய்யவும்.', correctAnswer: 'படி', hint: 'வார்த்தைகளை பார்ப்போம்.', explanation: 'படி = Read', maxAttempts: 3, timeLimitSeconds: 35, feedback: { correct: 'அருமை! புத்தகத்தை படிப்போம்.', incorrect: '"படி" என்ற சொல்லை முயற்சிக்கவும்.' }, position: 2 },
      ],
      order: 2,
    },
  ],

  'lesson-numbers-tamil': [
    {
      id: 'num-ta-s1',
      lessonId: 'lesson-numbers-tamil',
      title: 'எண்ணுதல்',
      titleI18n: { english: 'Counting up', tamil: 'எண்ணுதல்', hindi: 'गिनती' },
      textContent: 'தமிழில் ஒன்று முதல் ஐந்து வரை எண்ணுங்கள். ஒவ்வொரு எண்ணுக்கும் நிறம் சொல்லுங்கள்.',
      textContentI18n: { english: 'Count from one to five in Tamil. Name a colour for each number.', tamil: 'தமிழில் ஒன்று முதல் ஐந்து வரை எண்ணுங்கள். ஒவ்வொரு எண்ணுக்கும் நிறம் சொல்லுங்கள்.', hindi: 'तमिल में एक से पाँच तक गिनें। हर संख्या के लिए रंग बताइए।' },
      audioUrl: '/audio/num-ta-s1-narration.mp3',
      highlights: [
        { phrase: 'எண்ணுங்கள்', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'ஒன்று முதல் ஐந்து', emphasisType: 'underline', color: 'var(--accent-color)' },
      ],
      visuals: [{ imageUrl: '/visuals/numbers.svg', altText: 'Tamil numbers', relatedPhrase: 'எண்ணுங்கள்', placement: 'inline' }],
      interactions: [
        { id: 'numbers-ta-1', type: 'click', question: '"இரண்டு" க்கு அடுத்த தமிழ் எண்?', options: ['ஒன்று', 'மூன்று', 'ஐந்து'], correctAnswer: 1, hint: 'ஒன்று, இரண்டு, மூன்று எண்ணுங்கள்.', explanation: '"இரண்டு" க்கு பின் "மூன்று".', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'சிறப்பு! "இரண்டு" க்கு பின் "மூன்று".', incorrect: 'ஒன்று, இரண்டு, மூன்று எண்ணுங்கள்.' }, position: 0 },
        { id: 'numbers-ta-2', type: 'multiple_choice', question: '"நான்கு" க்கு அடுத்த தமிழ் எண்?', options: ['மூன்று', 'ஐந்து', 'ஆறு'], correctAnswer: 1, hint: 'நான்கு, ஐந்து எண்ணுங்கள்.', explanation: '"நான்கு" க்கு பின் "ஐந்து".', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'சரி! "நான்கு" க்கு பின் "ஐந்து".', incorrect: 'நான்கு, ஐந்து எண்ணுங்கள்.' }, position: 1 },
        { id: 'numbers-ta-3', type: 'multiple_choice', question: 'மூன்று பொருட்கள் உள்ள தொகுப்பு?', options: ['★★★', '★★', '★★★★'], correctAnswer: 0, hint: 'நட்சத்திரங்களை எண்ணுங்கள்.', explanation: 'மூன்று நட்சத்திரங்கள் = "மூன்று" (3).', maxAttempts: 3, timeLimitSeconds: 30, feedback: { correct: 'சிறந்த எண்ணல்!', incorrect: 'நட்சத்திரங்களை கவனமாக எண்ணுங்கள்.' }, position: 2 },
      ],
      order: 0,
    },
    {
      id: 'num-ta-s2',
      lessonId: 'lesson-numbers-tamil',
      title: 'எண் ஜோடிகள்',
      titleI18n: { english: 'Number pairs', tamil: 'எண் ஜோடிகள்', hindi: 'संख्या जोड़ी' },
      textContent: 'தமிழ் எண்களை சரியான எண்ணிக்கையிலான பொருட்களுடன் பொருத்துங்கள்.',
      textContentI18n: { english: 'Match Tamil numbers with the correct number of objects.', tamil: 'தமிழ் எண்களை சரியான எண்ணிக்கையிலான பொருட்களுடன் பொருத்துங்கள்.', hindi: 'तमिल संख्याओं को सही वस्तुओं की संख्या से मिलाएँ।' },
      audioUrl: '/audio/num-ta-s2-narration.mp3',
      highlights: [
        { phrase: 'பொருத்துங்கள்', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'எண்கள்', emphasisType: 'underline', color: 'var(--accent-color)' },
      ],
      visuals: [{ imageUrl: '/visuals/numbers.svg', altText: 'Counting objects', relatedPhrase: 'எண்கள்', placement: 'inline' }],
      interactions: [
        { id: 'num-ta-s2-1', type: 'multiple_choice', question: 'எத்தனை ஆப்பிள்கள் உள்ளன? (2 ஆப்பிள்கள்)', options: ['ஒன்று', 'இரண்டு', 'மூன்று'], correctAnswer: 1, hint: 'ஆப்பிள்களை கவனமாக எண்ணுங்கள்.', explanation: '"இரண்டு" (2) ஆப்பிள்கள்.', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'சரி! "இரண்டு" ஆப்பிள்கள்.', incorrect: 'மீண்டும் கவனமாக எண்ணுங்கள்.' }, position: 0 },
        { id: 'num-ta-s2-2', type: 'click', question: 'நான்கு நட்சத்திரங்களுக்கு (4) பொருந்தும் தமிழ் எண்ணை கிளிக் செய்யவும்.', options: ['மூன்று', 'நான்கு', 'ஐந்து'], correctAnswer: 1, hint: 'ஒவ்வொரு நட்சத்திரத்தையும் எண்ணுங்கள்.', explanation: 'நான்கு நட்சத்திரங்கள் = "நான்கு" (4).', maxAttempts: 3, timeLimitSeconds: 30, feedback: { correct: 'சிறந்த எண்ணல்! நான்கு நட்சத்திரங்கள் = "நான்கு".', incorrect: 'நட்சத்திரங்களை ஒன்றொன்றாக எண்ணுங்கள்.' }, position: 1 },
        { id: 'num-ta-s2-3', type: 'short_answer', question: 'எத்தனை புத்தகங்கள்? (3 புத்தகங்கள்) — தமிழில் எழுதவும்.', correctAnswer: 'மூன்று', hint: 'ஒவ்வொரு புத்தகத்தையும் எண்ணுங்கள்.', explanation: '"மூன்று" (3) புத்தகங்கள்.', maxAttempts: 3, timeLimitSeconds: 35, feedback: { correct: 'அருமை! "மூன்று" புத்தகங்கள்.', incorrect: 'எண்ணுங்கள்: ஒன்று, இரண்டு, மூன்று.' }, position: 2 },
      ],
      order: 1,
    },
    {
      id: 'num-ta-s3',
      lessonId: 'lesson-numbers-tamil',
      title: 'முன்னோக்கி எண்ணுதல்',
      titleI18n: { english: 'Counting forward', tamil: 'முன்னோக்கி எண்ணுதல்', hindi: 'आगे गिनना' },
      textContent: '"ஒன்று", "இரண்டு", "மூன்று" க்கு அடுத்த தமிழ் எண்ணை சொல்லுங்கள்.',
      textContentI18n: { english: 'Say the next Tamil number after "Ondru", "Irandu", and "Moondru".', tamil: '"ஒன்று", "இரண்டு", "மூன்று" க்கு அடுத்த தமிழ் எண்ணை சொல்லுங்கள்.', hindi: '"ओंड्रु", "इरण्डु", "मूंड्रु" के बाद आने वाली तमिल संख्या बोलें।' },
      audioUrl: '/audio/num-ta-s3-narration.mp3',
      highlights: [
        { phrase: 'அடுத்த எண்', emphasisType: 'background', color: '#a5d6a7' },
        { phrase: 'ஒன்று', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'இரண்டு', emphasisType: 'background', color: '#90caf9' },
        { phrase: 'மூன்று', emphasisType: 'background', color: '#ce93d8' },
      ],
      visuals: [
        { imageUrl: '/visuals/numbers.svg', altText: 'Number sequence', relatedPhrase: 'எண்', placement: 'inline' },
        { imageUrl: '/visuals/speech.svg', altText: 'Speaking numbers', relatedPhrase: 'சொல்லுங்கள்', placement: 'below' },
      ],
      interactions: [
        { id: 'num-ta-s3-1', type: 'multiple_choice', question: '"மூன்று" க்கு அடுத்த தமிழ் எண் எது?', options: ['இரண்டு', 'நான்கு', 'ஐந்து'], correctAnswer: 1, hint: 'ஒன்று, இரண்டு, மூன்று, பிறகு…', explanation: '"மூன்று" க்கு பின் "நான்கு".', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'சரி! "மூன்று" க்கு பின் "நான்கு".', incorrect: 'மூன்று, நான்கு எண்ணுங்கள்.' }, position: 0 },
        { id: 'num-ta-s3-2', type: 'true_false', question: '"ஐந்து" "நான்கு" க்கு பின் வருகிறதா?', correctAnswer: 'True', hint: 'எண்ணுங்கள்: நான்கு, ஐந்து.', explanation: 'ஆம், "நான்கு" க்கு பின் "ஐந்து" வருகிறது.', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'சரியாக! "ஐந்து" "நான்கு" க்கு பின் வருகிறது.', incorrect: '"நான்கு" இலிருந்து முன்னால் எண்ணுங்கள்.' }, position: 1 },
        { id: 'num-ta-s3-3', type: 'short_answer', question: '"இரண்டு" க்கு அடுத்த தமிழ் எண்ணை டைப் செய்யவும்.', correctAnswer: 'மூன்று', hint: 'எண்ணுங்கள்: ஒன்று, இரண்டு, மூன்று.', explanation: '"இரண்டு" க்கு பின் "மூன்று".', maxAttempts: 3, timeLimitSeconds: 35, feedback: { correct: 'அருமை! "இரண்டு" க்கு பின் "மூன்று".', incorrect: 'எண்ணுங்கள்: இரண்டு, மூன்று.' }, position: 2 },
      ],
      order: 2,
    },
  ],
};

export default lessonSectionSamplesTamil;
