/**
 * sectionSamplesHindi.js
 *
 * Static section data for Hindi language lessons.
 * Each lesson has 2–3 sections mirroring the English sectionSamples structure.
 */

const lessonSectionSamplesHindi = {
  'lesson-greetings-hindi': [
    {
      id: 'greet-hi-s1',
      lessonId: 'lesson-greetings-hindi',
      title: 'अभिवादन की मूल बातें',
      titleI18n: {
        english: 'Greeting basics',
        tamil: 'வாழ்த்தின் அடிப்படை',
        hindi: 'अभिवादन की मूल बातें',
      },
      textContent: 'नमस्ते! यह भाग शिष्ट तरीके से अभिवादन करना दिखाता है।',
      textContentI18n: {
        english: 'Namaste! This section shows how to greet politely in Hindi.',
        tamil: 'நமஸ்தே! இந்த பகுதி இந்தியில் மரியாதையுடன் எப்படி வாழ்த்துவது என்பதை காட்டுகிறது.',
        hindi: 'नमस्ते! यह भाग शिष्ट तरीके से अभिवादन करना दिखाता है।',
      },
      audioUrl: '/audio/greet-hi-s1-narration.mp3',
      highlights: [
        { phrase: 'नमस्ते', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'अभिवादन', emphasisType: 'underline', color: 'var(--accent-color)' },
        { phrase: 'शिष्ट', emphasisType: 'bold' },
      ],
      visuals: [
        { imageUrl: '/visuals/hello.svg', altText: 'Waving hand saying namaste', relatedPhrase: 'नमस्ते', placement: 'inline' },
        { imageUrl: '/visuals/how-are-you.svg', altText: 'People greeting each other politely', relatedPhrase: 'शिष्ट अभिवादन', placement: 'below' },
      ],
      interactions: [
        {
          id: 'greet-hi-1',
          type: 'true_false',
          question: 'क्या "नमस्ते" एक दोस्ताना अभिवादन है?',
          questionI18n: {
            english: 'Is "नमस्ते" (Namaste) a friendly greeting?',
            tamil: '"நமஸ்தே" (Namaste) என்பது நட்பான வாழ்த்தா?',
            hindi: 'क्या "नमस्ते" एक दोस्ताना अभिवादन है?',
          },
          correctAnswer: 'True',
          hint: 'यह भारत में सबसे आम अभिवादन है।',
          hintI18n: { english: 'This is the most common greeting in India.', tamil: 'இது இந்தியாவில் மிகவும் பொதுவான வாழ்த்து.', hindi: 'यह भारत में सबसे आम अभिवादन है।' },
          explanation: '"नमस्ते" किसी का अभिवादन करने का सामान्य और दोस्ताना तरीका है।',
          explanationI18n: { english: '"Namaste" is a common, friendly way to greet someone.', tamil: '"நமஸ்தே" என்பது ஒருவரை நட்பாக வாழ்த்தப் பயன்படும் பொதுவான சொல்.', hindi: '"नमस्ते" किसी का अभिवादन करने का सामान्य और दोस्ताना तरीका है।' },
          maxAttempts: 3, timeLimitSeconds: 25,
          feedback: { correct: 'बहुत बढ़िया! "नमस्ते" एक दोस्ताना अभिवादन है।', incorrect: 'अच्छी कोशिश। फिर से कोशिश करें।' },
          position: 0,
        },
        {
          id: 'greet-hi-2',
          type: 'multiple_choice',
          question: 'एक दोस्ताना अभिवादन चुनें।',
          questionI18n: { english: 'Choose a friendly greeting.', tamil: 'நட்பான வாழ்த்தைத் தேர்ந்தெடுக்கவும்.', hindi: 'एक दोस्ताना अभिवादन चुनें।' },
          options: ['नमस्ते', 'अलविदा', 'बाद में'],
          optionsI18n: [
            { english: 'Namaste (Hello)', tamil: 'நமஸ்தே (வணக்கம்)', hindi: 'नमस्ते' },
            { english: 'Goodbye', tamil: 'பிரியாவிடை', hindi: 'अलविदा' },
            { english: 'Later', tamil: 'பின்னர்', hindi: 'बाद में' },
          ],
          correctAnswer: 0,
          hint: 'बातचीत की शुरुआत में कहा जाने वाला शब्द।',
          explanation: '"नमस्ते" एक दोस्ताना अभिवादन है।',
          maxAttempts: 3, timeLimitSeconds: 25,
          feedback: { correct: 'हाँ! "नमस्ते" एक दोस्ताना अभिवादन है।', incorrect: 'अच्छी कोशिश। शुरुआत में कहा जाने वाला अभिवादन चुनें।' },
          position: 1,
        },
        {
          id: 'greet-hi-3',
          type: 'click',
          question: 'किसी का हाल-चाल पूछने वाला वाक्य चुनें।',
          questionI18n: { english: 'Click the phrase you use to ask about someone.', tamil: 'ஒருவரைப் பற்றி கேட்பதற்கு பயன்படுத்தும் வாக்கியத்தை கிளிக் செய்யவும்.', hindi: 'किसी का हाल-चाल पूछने वाला वाक्य चुनें।' },
          options: ['आप कैसे हैं?', 'यह कहाँ है?', 'फिर मिलेंगे'],
          optionsI18n: [
            { english: 'How are you?', tamil: 'நீங்கள் எப்படி இருக்கிறீர்கள்?', hindi: 'आप कैसे हैं?' },
            { english: 'Where is it?', tamil: 'அது எங்கே?', hindi: 'यह कहाँ है?' },
            { english: 'See you later', tamil: 'பின்னர் சந்திப்போம்', hindi: 'फिर मिलेंगे' },
          ],
          correctAnswer: 0,
          hint: 'यह भावनाओं/हाल-चाल के बारे में सवाल है।',
          explanation: '"आप कैसे हैं?" किसी का हाल-चाल पूछने के लिए कहा जाता है।',
          maxAttempts: 3, timeLimitSeconds: 30,
          feedback: { correct: 'बहुत अच्छा! यह हाल-चाल पूछने वाला सवाल है।', incorrect: 'अच्छी कोशिश। हाल-चाल वाला सवाल चुनें।' },
          position: 2,
        },
      ],
      order: 0,
    },
    {
      id: 'greet-hi-s2',
      lessonId: 'lesson-greetings-hindi',
      title: 'दोस्ताना वाक्य',
      titleI18n: {
        english: 'Friendly phrases',
        tamil: 'நட்பான சொற்றொடர்கள்',
        hindi: 'दोस्ताना वाक्य',
      },
      textContent: 'मुस्कान के साथ "नमस्ते" या "नमस्कार" कहें। "आप कैसे हैं?" पूछें।',
      textContentI18n: {
        english: 'Say "Namaste" or "Namaskar" with a smile. Ask "Aap kaise hain?"',
        tamil: 'சிரிப்புடன் "நமஸ்தே" அல்லது "நமஸ்கார்" சொல்லுங்கள். "ஆப் கைசே ஹைன்?" என்று கேளுங்கள்.',
        hindi: 'मुस्कान के साथ "नमस्ते" या "नमस्कार" कहें। "आप कैसे हैं?" पूछें।',
      },
      audioUrl: '/audio/greet-hi-s2-narration.mp3',
      highlights: [
        { phrase: 'नमस्ते', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'नमस्कार', emphasisType: 'background', color: '#90caf9' },
        { phrase: 'मुस्कान', emphasisType: 'underline', color: '#f06292' },
        { phrase: 'आप कैसे हैं?', emphasisType: 'background', color: '#a5d6a7' },
      ],
      visuals: [
        { imageUrl: '/visuals/hello.svg', altText: 'Friendly wave', relatedPhrase: 'नमस्ते', placement: 'inline' },
        { imageUrl: '/visuals/how-are-you.svg', altText: 'Friendly question', relatedPhrase: 'आप कैसे हैं?', placement: 'below' },
      ],
      interactions: [
        {
          id: 'greet-hi-s2-1',
          type: 'multiple_choice',
          question: '"नमस्ते" कहने का दोस्ताना तरीका कौन सा है?',
          questionI18n: { english: 'What is a friendly way to say hello in Hindi?', tamil: '"நமஸ்தே" சொல்லும் நட்பான வழி எது?', hindi: '"नमस्ते" कहने का दोस्ताना तरीका कौन सा है?' },
          options: ['नमस्कार!', 'चले जाओ!', 'अभी नहीं।'],
          optionsI18n: [
            { english: 'Namaskar!', tamil: 'நமஸ்கார்!', hindi: 'नमस्कार!' },
            { english: 'Go away!', tamil: 'போகுங்கள்!', hindi: 'चले जाओ!' },
            { english: 'Not now.', tamil: 'இப்போது இல்லை.', hindi: 'अभी नहीं।' },
          ],
          correctAnswer: 0,
          hint: 'गर्म और स्वागत करने वाला शब्द चुनें।',
          explanation: '"नमस्कार" एक दोस्ताना और औपचारिक अभिवादन है।',
          maxAttempts: 3, timeLimitSeconds: 25,
          feedback: { correct: 'बिल्कुल! "नमस्कार" बहुत दोस्ताना है।', incorrect: 'फिर से कोशिश करें। सबसे गर्म अभिवादन चुनें।' },
          position: 0,
        },
        {
          id: 'greet-hi-s2-2',
          type: 'true_false',
          question: 'क्या अभिवादन करते समय मुस्कुराना चाहिए?',
          questionI18n: { english: 'Should you smile when greeting someone?', tamil: 'ஒருவரை வாழ்த்தும்போது சிரிக்க வேண்டுமா?', hindi: 'क्या अभिवादन करते समय मुस्कुराना चाहिए?' },
          correctAnswer: 'True',
          hint: 'मुस्कान लोगों को स्वागत महसूस कराती है।',
          explanation: 'अभिवादन करते समय मुस्कुराना आपको दोस्ताना दिखाता है।',
          maxAttempts: 3, timeLimitSeconds: 25,
          feedback: { correct: 'बिल्कुल! मुस्कान अभिवादन को गर्म बनाती है।', incorrect: 'सोचिए कि लोगों को स्वागत क्या महसूस कराता है।' },
          position: 1,
        },
        {
          id: 'greet-hi-s2-3',
          type: 'short_answer',
          question: 'किसी से पूछने के लिए एक दोस्ताना हिन्दी सवाल टाइप करें।',
          questionI18n: { english: 'Type a friendly Hindi question you can ask someone.', tamil: 'ஒருவரிடம் கேட்கக்கூடிய நட்பான இந்தி கேள்வியை டைப் செய்யவும்.', hindi: 'किसी से पूछने के लिए एक दोस्ताना हिन्दी सवाल टाइप करें।' },
          correctAnswer: 'आप कैसे हैं',
          correctAnswerI18n: { english: 'How are you', tamil: 'நீங்கள் எப்படி இருக்கிறீர்கள்', hindi: 'आप कैसे हैं' },
          hint: 'उनके हाल-चाल के बारे में पूछें।',
          explanation: '"आप कैसे हैं?" दिखाता है कि आप उनकी परवाह करते हैं।',
          maxAttempts: 3, timeLimitSeconds: 35,
          feedback: { correct: 'बहुत अच्छा सवाल! बहुत दोस्ताना।', incorrect: '"आप कैसे हैं?" पूछकर देखें।' },
          position: 2,
        },
      ],
      order: 1,
    },
  ],

  'lesson-vocabulary-hindi': [
    {
      id: 'vocab-hi-s1',
      lessonId: 'lesson-vocabulary-hindi',
      title: 'रोज़मर्रा की वस्तुएँ',
      titleI18n: { english: 'Everyday objects', tamil: 'அன்றாட பொருட்கள்', hindi: 'रोज़मर्रा की वस्तुएँ' },
      textContent: 'आइए रोज़मर्रा की चीज़ों के लिए सरल हिन्दी शब्द सीखें।',
      textContentI18n: { english: 'Let\'s learn simple Hindi words for everyday items.', tamil: 'அன்றாட பொருட்களுக்கான எளிய இந்தி சொற்களை கற்றுக்கொள்வோம்.', hindi: 'आइए रोज़मर्रा की चीज़ों के लिए सरल हिन्दी शब्द सीखें।' },
      audioUrl: '/audio/vocab-hi-s1-narration.mp3',
      highlights: [
        { phrase: 'सरल शब्द', emphasisType: 'background', color: '#b39ddb' },
        { phrase: 'रोज़मर्रा', emphasisType: 'underline', color: 'var(--accent-color)' },
      ],
      visuals: [{ imageUrl: '/visuals/basic-words.svg', altText: 'Everyday objects', relatedPhrase: 'रोज़मर्रा', placement: 'inline' }],
      interactions: [
        { id: 'vocab-hi-1', type: 'multiple_choice', question: 'जिस चीज़ पर बैठते हैं, उसका हिन्दी शब्द?', options: ['कुर्सी', 'सेब', 'बारिश'], correctAnswer: 0, hint: 'फर्नीचर जिस पर बैठते हैं।', explanation: 'कुर्सी = Chair', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'हाँ! कुर्सी पर बैठते हैं।', incorrect: 'बैठने वाली चीज़ चुनें।' }, position: 0 },
        { id: 'vocab-hi-2', type: 'multiple_choice', question: 'खाने वाली चीज़ का हिन्दी शब्द?', options: ['सेब', 'कुर्सी', 'किताब'], correctAnswer: 0, hint: 'यह एक फल है।', explanation: 'सेब = Apple', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'सही! सेब एक फल है।', incorrect: 'फल चुनें।' }, position: 1 },
        { id: 'vocab-hi-3', type: 'click', question: 'पढ़ने वाली चीज़ का हिन्दी शब्द चुनें।', options: ['किताब', 'बादल', 'जूता'], correctAnswer: 0, hint: 'इसमें शब्द होते हैं।', explanation: 'किताब = Book', maxAttempts: 3, timeLimitSeconds: 30, feedback: { correct: 'बहुत अच्छा! किताब पढ़ी जाती है।', incorrect: 'पढ़ने वाली चीज़ चुनें।' }, position: 2 },
        { id: 'vocab-hi-4', type: 'short_answer', question: 'रहने की जगह का हिन्दी शब्द टाइप करें।', correctAnswer: 'घर', hint: 'जहाँ सोते हैं।', explanation: 'घर = Home', maxAttempts: 3, timeLimitSeconds: 35, feedback: { correct: 'बहुत अच्छा!', incorrect: '"घर" टाइप करें।' }, position: 3 },
      ],
      order: 0,
    },
    {
      id: 'vocab-hi-s2',
      lessonId: 'lesson-vocabulary-hindi',
      title: 'लोग और स्थान',
      titleI18n: { english: 'People and places', tamil: 'மக்கள் மற்றும் இடங்கள்', hindi: 'लोग और स्थान' },
      textContent: 'रोज़ाना दिखने वाले लोगों और जगहों के हिन्दी शब्दों का अभ्यास करें।',
      textContentI18n: { english: 'Practice Hindi words for people and places you see daily.', tamil: 'தினமும் பார்க்கும் மக்கள் மற்றும் இடங்களுக்கான இந்தி சொற்களை பயிற்சி செய்யுங்கள்.', hindi: 'रोज़ाना दिखने वाले लोगों और जगहों के हिन्दी शब्दों का अभ्यास करें।' },
      audioUrl: '/audio/vocab-hi-s2-narration.mp3',
      highlights: [
        { phrase: 'लोग', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'स्थान', emphasisType: 'background', color: '#90caf9' },
      ],
      visuals: [{ imageUrl: '/visuals/sun.svg', altText: 'Daily life', relatedPhrase: 'रोज़ाना', placement: 'inline' }],
      interactions: [
        { id: 'vocab-hi-s2-1', type: 'multiple_choice', question: 'खाना खरीदने कहाँ जाते हैं?', options: ['दुकान', 'आसमान', 'पेड़'], correctAnswer: 0, hint: 'वहाँ खरीदारी करते हैं।', explanation: 'दुकान = Store — जहाँ सामान खरीदते हैं।', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'हाँ! दुकान से खाना खरीदते हैं।', incorrect: 'खरीदारी की जगह सोचें।' }, position: 0 },
        { id: 'vocab-hi-s2-2', type: 'click', question: 'पढ़ाने वाले व्यक्ति का हिन्दी शब्द चुनें।', options: ['शिक्षक', 'पत्ता', 'दरवाज़ा'], correctAnswer: 0, hint: 'यह व्यक्ति आपको सीखने में मदद करता है।', explanation: 'शिक्षक = Teacher', maxAttempts: 3, timeLimitSeconds: 30, feedback: { correct: 'बिल्कुल! शिक्षक पढ़ाते हैं।', incorrect: 'पढ़ाने वाले व्यक्ति का शब्द चुनें।' }, position: 1 },
        { id: 'vocab-hi-s2-3', type: 'short_answer', question: 'परिवार के किसी सदस्य का हिन्दी शब्द टाइप करें।', correctAnswer: 'माँ', hint: 'माँ, पिता, बहन के बारे में सोचें।', explanation: 'परिवार के सदस्य: माँ, पिता, बहन, भाई।', maxAttempts: 3, timeLimitSeconds: 35, feedback: { correct: 'बहुत अच्छा! यह परिवार का सदस्य है।', incorrect: '"माँ", "पिता", या "बहन" जैसे शब्द आज़माएँ।' }, position: 2 },
      ],
      order: 1,
    },
    {
      id: 'vocab-hi-s3',
      lessonId: 'lesson-vocabulary-hindi',
      title: 'क्रिया शब्द',
      titleI18n: { english: 'Action words', tamil: 'செயல் சொற்கள்', hindi: 'क्रिया शब्द' },
      textContent: 'सरल हिन्दी क्रिया शब्द सीखें जैसे "खाना", "चलना", और "पढ़ना"।',
      textContentI18n: { english: 'Learn simple Hindi action words like "khaana", "chalna", and "padhna".', tamil: 'எளிய இந்தி செயல் சொற்களை கற்றுக்கொள்ளுங்கள்: "கானா", "சல்னா", "பட்னா".', hindi: 'सरल हिन्दी क्रिया शब्द सीखें जैसे "खाना", "चलना", और "पढ़ना"।' },
      audioUrl: '/audio/vocab-hi-s3-narration.mp3',
      highlights: [
        { phrase: 'क्रिया शब्द', emphasisType: 'background', color: '#a5d6a7' },
        { phrase: 'खाना', emphasisType: 'background', color: '#ffab91' },
        { phrase: 'चलना', emphasisType: 'background', color: '#90caf9' },
        { phrase: 'पढ़ना', emphasisType: 'background', color: '#ce93d8' },
      ],
      visuals: [{ imageUrl: '/visuals/speech.svg', altText: 'Speaking action words', relatedPhrase: 'बोलें', placement: 'below' }],
      interactions: [
        { id: 'vocab-hi-s3-1', type: 'multiple_choice', question: 'खाने के साथ कौन सी क्रिया करते हैं?', options: ['खाना', 'उड़ना', 'सोना'], correctAnswer: 0, hint: 'भूख लगने पर यह करते हैं।', explanation: 'खाना = Eat', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'सही! भोजन खाते हैं।', incorrect: 'भोजन के साथ क्या करते हैं सोचें।' }, position: 0 },
        { id: 'vocab-hi-s3-2', type: 'click', question: 'पैरों से की जाने वाली क्रिया चुनें।', options: ['चलना', 'सोचना', 'गाना'], correctAnswer: 0, hint: 'एक जगह से दूसरी जगह जाना।', explanation: 'चलना = Walk', maxAttempts: 3, timeLimitSeconds: 30, feedback: { correct: 'हाँ! पैरों से चलते हैं।', incorrect: 'पैरों वाली क्रिया चुनें।' }, position: 1 },
        { id: 'vocab-hi-s3-3', type: 'short_answer', question: 'किताब के साथ की जाने वाली क्रिया टाइप करें।', correctAnswer: 'पढ़ना', hint: 'शब्दों को देखते हैं।', explanation: 'पढ़ना = Read', maxAttempts: 3, timeLimitSeconds: 35, feedback: { correct: 'बहुत अच्छा! किताब पढ़ते हैं।', incorrect: '"पढ़ना" शब्द आज़माएँ।' }, position: 2 },
      ],
      order: 2,
    },
  ],

  'lesson-numbers-hindi': [
    {
      id: 'num-hi-s1',
      lessonId: 'lesson-numbers-hindi',
      title: 'गिनती',
      titleI18n: { english: 'Counting up', tamil: 'எண்ணுதல்', hindi: 'गिनती' },
      textContent: 'हिन्दी में एक से पाँच तक गिनें। हर संख्या के लिए रंग बताइए।',
      textContentI18n: { english: 'Count from one to five in Hindi. Name a colour for each number.', tamil: 'இந்தியில் ஒன்று முதல் ஐந்து வரை எண்ணுங்கள். ஒவ்வொரு எண்ணுக்கும் நிறம் சொல்லுங்கள்.', hindi: 'हिन्दी में एक से पाँच तक गिनें। हर संख्या के लिए रंग बताइए।' },
      audioUrl: '/audio/num-hi-s1-narration.mp3',
      highlights: [
        { phrase: 'गिनें', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'एक से पाँच', emphasisType: 'underline', color: 'var(--accent-color)' },
      ],
      visuals: [{ imageUrl: '/visuals/numbers.svg', altText: 'Hindi numbers', relatedPhrase: 'गिनें', placement: 'inline' }],
      interactions: [
        { id: 'numbers-hi-1', type: 'click', question: '"दो" के बाद कौन सी हिन्दी संख्या आती है?', options: ['एक', 'तीन', 'पाँच'], correctAnswer: 1, hint: 'एक, दो, तीन गिनें।', explanation: '"दो" के बाद "तीन" आता है।', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'बहुत बढ़िया! "दो" के बाद "तीन"।', incorrect: 'एक, दो, तीन गिनें।' }, position: 0 },
        { id: 'numbers-hi-2', type: 'multiple_choice', question: '"चार" के बाद कौन सी हिन्दी संख्या?', options: ['तीन', 'पाँच', 'छह'], correctAnswer: 1, hint: 'चार, पाँच गिनें।', explanation: '"चार" के बाद "पाँच"।', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'सही! "चार" के बाद "पाँच"।', incorrect: 'चार, पाँच गिनें।' }, position: 1 },
        { id: 'numbers-hi-3', type: 'multiple_choice', question: 'किस समूह में तीन वस्तुएँ हैं?', options: ['★★★', '★★', '★★★★'], correctAnswer: 0, hint: 'तारों को गिनें।', explanation: 'तीन तारे = "तीन" (3)।', maxAttempts: 3, timeLimitSeconds: 30, feedback: { correct: 'बहुत अच्छी गिनती!', incorrect: 'तारों को ध्यान से गिनें।' }, position: 2 },
      ],
      order: 0,
    },
    {
      id: 'num-hi-s2',
      lessonId: 'lesson-numbers-hindi',
      title: 'संख्या जोड़ी',
      titleI18n: { english: 'Number pairs', tamil: 'எண் ஜோடிகள்', hindi: 'संख्या जोड़ी' },
      textContent: 'संख्याओं को सही वस्तुओं की संख्या से मिलाएँ।',
      textContentI18n: { english: 'Match Hindi numbers with the correct number of objects.', tamil: 'இந்தி எண்களை சரியான எண்ணிக்கையிலான பொருட்களுடன் பொருத்துங்கள்.', hindi: 'संख्याओं को सही वस्तुओं की संख्या से मिलाएँ।' },
      audioUrl: '/audio/num-hi-s2-narration.mp3',
      highlights: [
        { phrase: 'मिलाएँ', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'संख्या', emphasisType: 'underline', color: 'var(--accent-color)' },
      ],
      visuals: [{ imageUrl: '/visuals/numbers.svg', altText: 'Counting objects', relatedPhrase: 'संख्या', placement: 'inline' }],
      interactions: [
        { id: 'num-hi-s2-1', type: 'multiple_choice', question: 'कितने सेब हैं? (2 सेब)', options: ['एक', 'दो', 'तीन'], correctAnswer: 1, hint: 'सेब गिनें।', explanation: '"दो" (2) सेब हैं।', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'सही! "दो" सेब हैं।', incorrect: 'फिर से गिनें।' }, position: 0 },
        { id: 'num-hi-s2-2', type: 'click', question: 'चार तारों (4) से मेल खाने वाली हिन्दी संख्या चुनें।', options: ['तीन', 'चार', 'पाँच'], correctAnswer: 1, hint: 'हर तारा गिनें।', explanation: 'चार तारे = "चार" (4)।', maxAttempts: 3, timeLimitSeconds: 30, feedback: { correct: 'शानदार गिनती! चार तारे = "चार"।', incorrect: 'तारे एक-एक करके गिनें।' }, position: 1 },
        { id: 'num-hi-s2-3', type: 'short_answer', question: 'कितनी किताबें हैं? (3 किताबें) — हिन्दी में लिखें।', correctAnswer: 'तीन', hint: 'हर किताब गिनें।', explanation: '"तीन" (3) किताबें हैं।', maxAttempts: 3, timeLimitSeconds: 35, feedback: { correct: 'बहुत अच्छा! "तीन" किताबें गिनीं।', incorrect: 'गिनें: एक, दो, तीन।' }, position: 2 },
      ],
      order: 1,
    },
    {
      id: 'num-hi-s3',
      lessonId: 'lesson-numbers-hindi',
      title: 'आगे गिनना',
      titleI18n: { english: 'Counting forward', tamil: 'முன்னோக்கி எண்ணுதல்', hindi: 'आगे गिनना' },
      textContent: '"एक", "दो", और "तीन" के बाद आने वाली हिन्दी संख्या बोलें।',
      textContentI18n: { english: 'Say the next Hindi number after "Ek", "Do", and "Teen".', tamil: '"ஏக்", "தோ", "தீன்" க்கு அடுத்த இந்தி எண்ணை சொல்லுங்கள்.', hindi: '"एक", "दो", और "तीन" के बाद आने वाली हिन्दी संख्या बोलें।' },
      audioUrl: '/audio/num-hi-s3-narration.mp3',
      highlights: [
        { phrase: 'अगली संख्या', emphasisType: 'background', color: '#a5d6a7' },
        { phrase: 'एक', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'दो', emphasisType: 'background', color: '#90caf9' },
        { phrase: 'तीन', emphasisType: 'background', color: '#ce93d8' },
      ],
      visuals: [
        { imageUrl: '/visuals/numbers.svg', altText: 'Number sequence', relatedPhrase: 'संख्या', placement: 'inline' },
        { imageUrl: '/visuals/speech.svg', altText: 'Speaking numbers', relatedPhrase: 'बोलें', placement: 'below' },
      ],
      interactions: [
        { id: 'num-hi-s3-1', type: 'multiple_choice', question: '"तीन" के बाद कौन सी हिन्दी संख्या आती है?', options: ['दो', 'चार', 'पाँच'], correctAnswer: 1, hint: 'एक, दो, तीन, फिर…', explanation: '"तीन" के बाद "चार" आता है।', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'सही! "तीन" के बाद "चार"।', incorrect: 'तीन, चार गिनें।' }, position: 0 },
        { id: 'num-hi-s3-2', type: 'true_false', question: 'क्या "पाँच" "चार" के बाद आता है?', correctAnswer: 'True', hint: 'गिनें: चार, पाँच।', explanation: 'हाँ, "चार" के बाद "पाँच" आता है।', maxAttempts: 3, timeLimitSeconds: 25, feedback: { correct: 'बिल्कुल! "पाँच" "चार" के बाद आता है।', incorrect: '"चार" से आगे गिनें।' }, position: 1 },
        { id: 'num-hi-s3-3', type: 'short_answer', question: '"दो" के बाद आने वाली हिन्दी संख्या टाइप करें।', correctAnswer: 'तीन', hint: 'गिनें: एक, दो, तीन।', explanation: '"दो" के बाद "तीन" आता है।', maxAttempts: 3, timeLimitSeconds: 35, feedback: { correct: 'बहुत अच्छा! "दो" के बाद "तीन"।', incorrect: 'गिनें: दो, तीन।' }, position: 2 },
      ],
      order: 2,
    },
  ],
};

export default lessonSectionSamplesHindi;
